# phase2_cases_part2.py
# Manila Law College - Statutory Construction Case Digests
# Chapter III-B: Considerations within the Statute (Cases 32 to 41)

cases_p2_part2 = [
    {
        "num": 32,
        "title": "People of the Philippines v. Patricio Garcia",
        "citation": "G.R. No. L-2873 | February 28, 1950 | 85 Phil. 651 | En Banc | Ponente: J. Tuason",
        "plaintiff": "People of the Philippines (Appellee)",
        "defendant": "Patricio Garcia (Appellant)",
        "court": "Court of First Instance of Manila",
        "nature": "Appeal from a criminal conviction for Robbery with Homicide involving the statutory benefit of suspended sentence under Article 80 of the Revised Penal Code.",
        "facts": "Patricio Garcia committed robbery with homicide when he was 17 years old (a minor). However, due to delays in apprehension and trial, by the time the judgment of conviction was rendered by the trial court, Garcia had already reached 20 years of age (past the age of 18). Article 80 of the Revised Penal Code provided that when a minor under 18 years of age is accused of a crime, the court shall suspend proceedings and commit him to a correctional institution until he reaches the age of majority. The trial court refused to apply Article 80, holding that the accused was no longer under 18 at the time of judgment. Garcia appealed, arguing that minority at the time of the COMMISSION of the crime governs.",
        "plain_facts": "A 17-year-old boy committed a robbery. By the time his trial finished, he was 20 years old. The law (Article 80 RPC) gives juvenile delinquents suspended sentences instead of prison, sending them to reformatories. The trial judge refused to grant the youth reformatory benefits, saying the accused was already an adult on the day of sentencing. The Supreme Court ruled that age at the time the crime was committed determines whether you get the benefit of the youth rehabilitation law.",
        "issue": "Whether or not the benefits of suspended sentence under Article 80 of the Revised Penal Code apply to an accused who was a minor at the time of the commission of the crime, but who reached majority during trial.",
        "issue_plain": "Does a teenager get the benefit of the juvenile suspended sentence law if he was 17 when he committed the crime, but turned 20 before the judge finished the trial?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether Article 80 RPC applies based on the age of the offender at the time of the commission of the offense rather than at the time of trial or judgment, testing the canon Favorabilia Sunt Amplianda, Odiosa Restringenda (favorable things should be enlarged, hateful things restricted) and In Dubio Pro Reo.\"",
        "answer": "YES. The age of the accused at the TIME OF THE COMMISSION of the offense governs. Penal laws providing beneficial treatment or mitigation to juvenile offenders are liberally construed in favor of the accused (Favorabilia sunt amplianda, odiosa restringenda).",
        "answer_plain": "Yes. What matters is how old the youth was when he committed the act. Because penal laws that help the accused must be interpreted broadly and generously, court delays cannot steal away the reformatory rights granted to minors.",
        "answer_recite": "\"Yes, Sir/Ma'am. Under the canon Favorabilia sunt amplianda, odiosa restringenda (matters of favor are enlarged, and hateful matters restricted) and strict construction of penal laws in favor of the accused, the Supreme Court held that the age at the time of the commission of the crime controls, preserving juvenile reformatory benefits.\"",
        "legal_basis": [
            ("1. Article 80, Revised Penal Code (as amended):", "Suspension of sentence and commitment of juvenile delinquents to training institutions."),
            ("2. Favorabilia Sunt Amplianda, Odiosa Restringenda (favorable things should be enlarged, odious things restricted):", "Beneficial statutory provisions are interpreted broadly, while punitive or restrictive rules are interpreted narrowly."),
            ("3. In Favorem Libertatis / In Dubio Pro Reo (in favor of liberty / in doubt, rule for the accused):", "All doubts in criminal statutory provisions are resolved in favor of the accused.")
        ],
        "legal_basis_plain": "Article 80 RPC, Favorabilia Sunt Amplianda, Odiosa Restringenda, and In Favorem Libertatis.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Article 80 RPC, governed by Favorabilia sunt amplianda, odiosa restringenda (favorable things enlarged, hateful things restricted) and In favorem libertatis (in favor of personal liberty).\"",
        "analysis": [
            ("1. Purpose of Juvenile Delinquency Legislation:", "The primary intention of Article 80 RPC is reformative and rehabilitative rather than retributive, recognizing the immature discernment of youthful offenders."),
            ("2. Prevention of Prejudice Through Court Delay:", "An accused should not be deprived of statutory leniency and juvenile protection simply because judicial proceedings were delayed through no fault of his own."),
            ("3. Liberal Construction of Beneficial Provisions:", "Statutes that alleviate the harshness of criminal punishment must be given the most expansive, favorable interpretation permitted by reason.")
        ],
        "analysis_plain": "The purpose of youth laws is to reform young minds. If the law were tied to the date of judgment, a slow court schedule would punish the boy as an adult, which contradicts the whole reason the legislature passed the law. The Court ruled that beneficial laws must be stretched to protect human rehabilitation.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied Favorabilia Sunt Amplianda. The purpose of juvenile legislation is rehabilitation. Interpreting the law to require minority at the date of sentence would make youth benefits depend on accidental court delays, defeating the humane intent of the legislature.\"",
        "conclusion": "The Supreme Court SET ASIDE the prison sentence and ORDERED the trial court to apply the rehabilitative benefits of Article 80 of the Revised Penal Code.",
        "conclusion_plain": "The youth was granted the benefits of juvenile rehabilitation rather than adult prison.",
        "conclusion_recite": "\"The Supreme Court set aside the regular prison penalty, holding that age at the time of the offense governs under the rule of liberal construction of beneficial penal laws.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Favorabilia Sunt Amplianda, Odiosa Restringenda",
        "latin_maxims": [
            ("Favorabilia sunt amplianda, odiosa restringenda (favorable things should be enlarged, hateful things restricted)", "Matters of favor are to be extended, matters of burden or penalty are to be restrained.", "Beneficial statutory provisions for juvenile offenders must be given the widest possible scope."),
            ("In favorem libertatis (in favor of personal liberty)", "In favor of liberty.", "Penal and procedural statutes are interpreted to favor personal liberty and human rehabilitation."),
            ("Ratio legis est anima legis (the reason of the law is the soul of the law)", "The reason of the law is the soul of the law.", "The rehabilitative objective of youth laws determines their proper statutory scope.")
        ],
        "primary_maxim": "Favorabilia sunt amplianda, odiosa restringenda\n(favorable things should be enlarged, hateful things restricted / beneficial juvenile penal provisions are given broad, humane construction)",
        "secondary_maxims": "• In favorem libertatis (in favor of liberty)\n• Ratio legis est anima legis (the reason of the law is its soul)",
        "violation_text": "The trial court applied a harsh, restrictive interpretation that converted court docket delays into an instrument to strip a juvenile offender of statutory reformatory benefits.",
        "execution_text": "Liberal Construction of Beneficial Statutes: Statutory provisions that mitigate criminal penalties or provide rehabilitation must be interpreted broadly in favor of the beneficiary.",
        "statcon_plain": "When a law offers mercy, pardon, or rehabilitation, judges must interpret it broadly to give the person a second chance.",
        "statcon_recite": "\"Sir/Ma'am, People v. Garcia is the foremost authority on Favorabilia sunt amplianda, odiosa restringenda: beneficial provisions in criminal law are interpreted expansively in favor of the accused.\""
    },
    {
        "num": 33,
        "title": "People of the Philippines v. The Honorable Sandiganbayan (Fourth Division) and Ceferino S. Paredes, Jr.",
        "citation": "G.R. Nos. 147706-07 | February 16, 2005 | 451 SCRA 413 | First Division | Ponente: J. Quisumbing",
        "plaintiff": "People of the Philippines (Petitioner)",
        "defendant": "The Honorable Sandiganbayan (Fourth Division) and Ceferino S. Paredes, Jr. (Respondents)",
        "court": "Sandiganbayan (Fourth Division)",
        "nature": "Petition for Certiorari under Rule 65 assailing Sandiganbayan resolution allowing a plea of guilty to a lesser offense in a prosecution under R.A. No. 3019 (Anti-Graft and Corrupt Practices Act).",
        "facts": "Atty. Ceferino S. Paredes, Jr., former Provincial Attorney and Governor of Agusan del Sur, was charged before the Sandiganbayan with violation of Section 3(e) of Republic Act No. 3019 (Anti-Graft and Corrupt Practices Act) for unlawfully applying for and obtaining free patents over public land. During trial, Paredes offered to plead guilty to the lesser offense of Public Land Act violations. The Special Prosecutor consented, and the Sandiganbayan accepted the plea. The Solicitor General petitioned the Supreme Court, contending that the Sandiganbayan violated the Rules of Criminal Procedure because RA 3019 does not allow plea bargaining to an offense that is not necessarily included in the offense charged.",
        "plain_facts": "A former governor was criminally charged with graft under the Anti-Graft Law for grabbing public land. In court, he negotiated a deal to plead guilty to a minor land registration offense instead of graft. The Sandiganbayan accepted the deal. The People challenged this before the Supreme Court, arguing that under the Rules of Court, you can only plead guilty to a lesser offense if all the legal elements of the lesser offense are naturally included in the original charge. The Supreme Court ruled that the plea bargaining was illegal because the lesser offense was not legally included in the graft charge.",
        "issue": "Whether or not an accused charged with violation of Section 3(e) of R.A. No. 3019 may validly plead guilty to a lesser offense under the Public Land Act that is not necessarily included in the offense charged.",
        "issue_plain": "Can an accused plead guilty to a minor crime if that minor crime is not legally included inside the graft charge filed by the prosecutor?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether plea bargaining to a lesser offense requires that the lesser crime be necessarily included in the charged offense under Rule 116, testing the rule on Construing a Statute as a Whole (Ut Res Magis Valeat Quam Pereat) and Verba Legis.\"",
        "answer": "NO. A plea of guilty to a lesser offense is valid ONLY IF the lesser offense is NECESSARILY INCLUDED in the offense charged. The Sandiganbayan committed grave abuse of discretion by accepting a plea to an offense with entirely different statutory elements.",
        "answer_plain": "No. Under procedural law, a lesser offense must be a smaller piece already contained inside the bigger crime charged. Because the Public Land Act has completely different elements from Graft, the plea bargain was totally illegal.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court held that under Section 2, Rule 116 of the Rules of Court, plea bargaining requires that the lesser offense be necessarily included in the offense charged. Interpreting the procedural rule as an integrated whole, courts have no authority to approve plea bargains to extraneous crimes.\"",
        "legal_basis": [
            ("1. Section 2, Rule 116, Revised Rules of Criminal Procedure:", "Governs plea of guilty to a lesser offense necessarily included in the offense charged."),
            ("2. Section 3(e), Republic Act No. 3019 (Anti-Graft and Corrupt Practices Act):", "Statutory elements of graft and corruption."),
            ("3. Ut Res Magis Valeat Quam Pereat (that the thing may rather have effect than perish):", "Procedural rules on criminal pleading must be construed as a consistent, integrated whole."),
            ("4. Verba Legis Non Est Recedendum (from the words of the statute there should be no departure):", "The requirement of 'necessarily included' is mandatory.")
        ],
        "legal_basis_plain": "Rule 116 Sec 2, Section 3(e) RA 3019, Ut Res Magis Valeat Quam Pereat, and Verba Legis.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 2, Rule 116 of the Rules of Court, interpreted under Ut res magis valeat quam pereat (construction to preserve the whole efficacy of the law) and Verba legis non est recedendum.\"",
        "analysis": [
            ("1. Statutory Definition of Included Offenses:", "An offense is necessarily included in another when some of the essential elements of the crime charged constitute the lesser offense. The Public Land violation had elements outside Section 3(e) of RA 3019."),
            ("2. Construction of Rule 116 as a Whole:", "Plea bargaining is not an unfettered compromise; it is strictly bounded by the structural requirements of procedural due process and statutory definitions."),
            ("3. Nullity of Ultra Vires Plea:", "The Sandiganbayan exceeded its jurisdiction by inventing an unauthorized plea bargain that subverted the anti-graft statute.")
        ],
        "analysis_plain": "The Court explained that a lesser crime must fit inside the bigger crime like a Russian nesting doll. If the lesser crime contains foreign elements that were never alleged in the information, the court cannot accept the plea. Rules must be enforced as a coherent whole.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied statutory harmonization. Procedural rules must be construed as a whole to give effect to every part (Ut Res Magis Valeat Quam Pereat). The trial court cannot disregard the mandatory statutory requirement that the lesser offense be legally included in the charge.\"",
        "conclusion": "The Supreme Court GRANTED the petition, ANNULLED the Sandiganbayan resolution approving the plea of guilty to the lesser offense, and ORDERED trial on the original graft information to proceed.",
        "conclusion_plain": "The plea bargain was struck down and the governor was ordered to stand trial for graft.",
        "conclusion_recite": "\"The Supreme Court annulled the plea bargain and reinstated the original graft trial, holding that procedural rules on included offenses must be strictly enforced as a whole.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Statute Construed as a Whole (Ut Res Magis Valeat Quam Pereat)",
        "latin_maxims": [
            ("Ut res magis valeat quam pereat (that the thing may rather have effect than perish)", "That the thing may have effect rather than perish.", "Procedural statutes and criminal rules must be construed as a harmonious whole to make every provision effective."),
            ("Verba legis non est recedendum (from the words of the statute there should be no departure)", "From the words of the statute there must be no departure.", "The statutory requirement of 'necessarily included' cannot be ignored by trial courts."),
            ("Ex antecedentibus et consequentibus fit optima interpretatio (the best interpretation is made from what precedes and what follows)", "The best interpretation arises from comparing preceding and following parts.", "Rules on criminal pleading must be interpreted in connection with all related procedural provisions.")
        ],
        "primary_maxim": "Ut res magis valeat quam pereat\n(that the thing may have effect rather than perish / procedural codes must be construed as an integrated, effective whole)",
        "secondary_maxims": "• Ex antecedentibus et consequentibus fit optima interpretatio (best interpretation from the whole context)\n• Verba legis non est recedendum (from statutory words no departure)",
        "violation_text": "The Sandiganbayan created an ad-hoc plea bargain that severed Section 2, Rule 116 from its statutory requirement of necessary inclusion.",
        "execution_text": "Holistic Construction of Procedural Codes: Every part of a statute or procedural rule must be construed in connection with every other part to create a consistent, unbroken system of law.",
        "statcon_plain": "Rules and laws cannot be chopped up into pieces; every sentence must be read alongside the rest of the rule so it works properly.",
        "statcon_recite": "\"Sir/Ma'am, People v. Sandiganbayan demonstrates that procedural rules on plea bargaining must be construed as an integrated whole—Ut res magis valeat quam pereat.\""
    },
    {
        "num": 34,
        "title": "Pelizloy Realty Corporation v. The Province of Benguet",
        "citation": "G.R. No. 183137 | April 10, 2013 | 695 SCRA 491 | First Division | Ponente: J. Bersamin",
        "plaintiff": "Pelizloy Realty Corporation (Petitioner)",
        "defendant": "The Province of Benguet (Respondent)",
        "court": "Regional Trial Court of La Trinidad, Benguet (Branch 63)",
        "nature": "Petition for Review on Certiorari under Rule 45 assailing the validity of Benguet Provincial Tax Ordinance No. 05-85 imposing amusement taxes on resorts and swimming pools.",
        "facts": "Pelizloy Realty Corporation owns Palm Grove Resort in Tuba, Benguet, which features swimming pools and recreational facilities. The Province of Benguet enacted Provincial Tax Ordinance No. 05-85, Section 59 of which levied a 10% amusement tax on gross receipts of resorts, swimming pools, bath houses, and other tourist establishments. Pelizloy challenged the ordinance, arguing that under Section 140 of the Local Government Code (LGC), provinces can levy amusement taxes ONLY on theaters, cinemas, concert halls, circuses, and other places of amusement where one enters primarily to VIEW a dramatic or musical exhibition, invoking Ejusdem Generis.",
        "plain_facts": "The Province of Benguet passed a tax ordinance making resorts, swimming pools, and bath houses pay a 10% amusement tax. A resort owner objected, arguing that under the Local Government Code, amusement taxes can only be placed on show-business venues like movie theaters, cinemas, concert halls, and circuses. The Supreme Court ruled in favor of the resort, applying Ejusdem Generis: swimming pools and resorts are places for physical exercise and recreation, not places where you sit and watch theatrical shows.",
        "issue": "Whether or not provinces have the statutory authority under Section 140 of the Local Government Code to impose amusement taxes on resorts, swimming pools, and bath houses.",
        "issue_plain": "Can a province collect amusement tax from resorts and swimming pools when the Local Government Code only authorizes amusement tax on theaters, cinemas, and concert halls?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether Section 140 of the Local Government Code authorizes an amusement tax on resorts and swimming pools, testing the canon of Ejusdem Generis (of the same kind) and strict construction of local taxing powers.\"",
        "answer": "NO. Section 140 of the Local Government Code does NOT authorize provinces to tax resorts and swimming pools. Under the rule of Ejusdem Generis, the general term 'other places of amusement' is restricted to venues of the same kind as theaters, cinemas, concert halls, and circuses.",
        "answer_plain": "No. Under Ejusdem Generis, when a law gives a specific list (theaters, cinemas, concert halls) followed by general words ('other places of amusement'), the general words only include things of the exact same kind—namely, places where you watch performances, not places where you swim.",
        "answer_recite": "\"No, Sir/Ma'am. Applying Ejusdem Generis (of the same kind), the Supreme Court held that the phrase 'other places of amusement' in Section 140 of the LGC is confined to venues for viewing theatrical or artistic performances. Resorts and swimming pools involve active physical recreation and cannot be taxed under Section 140.\"",
        "legal_basis": [
            ("1. Section 140, Republic Act No. 7160 (Local Government Code of 1991):", "Authorizes provinces to levy amusement taxes on 'theaters, cinemas, concert halls, circuses, boxing stadia, and other places of amusement'."),
            ("2. Ejusdem Generis (of the same kind or class):", "Where general words follow an enumeration of specific classes of persons or things, the general words are construed as applying only to things of the same general class."),
            ("3. Strict Construction of Taxing Grants:", "Delegated taxing powers to local government units are strictly construed against the local government and liberally in favor of the taxpayer.")
        ],
        "legal_basis_plain": "Section 140 LGC, Ejusdem Generis, and strict construction of delegated taxing powers.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 140 of RA 7160 (LGC), governed by Ejusdem generis (of the same kind or nature) and strictissimi juris in local taxation.\"",
        "analysis": [
            ("1. Application of Ejusdem Generis:", "Section 140 explicitly enumerates theaters, cinemas, concert halls, circuses, and boxing stadia. The common, unifying characteristic is that they are venues for visual or performing entertainment."),
            ("2. Distinct Character of Resorts and Pools:", "Resorts and swimming pools are venues for active recreation, rest, and sports, not spectator entertainment exhibitions."),
            ("3. Ultra Vires Local Legislation:", "By including resorts and swimming pools in its tax ordinance, the Province of Benguet exceeded the statutory limits of Section 140 LGC, making that portion of the ordinance null and void.")
        ],
        "analysis_plain": "The specific list in the law consists entirely of spectator venues where audiences sit down to watch a show. A swimming pool is a place where you put on swimwear and do exercise. Because swimming is completely different from watching a concert, Ejusdem Generis forbids the province from taxing pools under that section.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied Ejusdem Generis. The specific enumerations in Section 140 share the common feature of visual spectator entertainment. Applying Ejusdem Generis, 'other places of amusement' cannot be stretched to cover swimming pools and resorts, rendering the provincial tax ultra vires.\"",
        "conclusion": "The Supreme Court GRANTED the petition, DECLARED Section 59 of Benguet Provincial Tax Ordinance No. 05-85 NULL AND VOID insofar as it levied amusement tax on resorts and swimming pools, and ORDERED the province to drop the assessments.",
        "conclusion_plain": "The resort won; the swimming pool tax was declared illegal and cancelled.",
        "conclusion_recite": "\"The Supreme Court struck down the provincial amusement tax on resorts and pools under the doctrine of Ejusdem Generis.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Ejusdem Generis (Of the Same Kind)",
        "latin_maxims": [
            ("Ejusdem generis (of the same kind or class)", "Of the same kind.", "General words following an enumeration of specific items are restricted to things of the same class as those specifically mentioned."),
            ("Noscitur a sociis (a thing is known by its associates)", "It is known by its companions.", "The meaning of 'other places of amusement' is defined by its associated words: theaters, cinemas, and concert halls."),
            ("Strictissimi juris (of the strictest interpretation)", "Of the strictest law.", "Delegated taxing powers of local government units are strictly construed against the municipality.")
        ],
        "primary_maxim": "Ejusdem generis\n(of the same kind or class / 'other places of amusement' in Section 140 LGC is restricted to theatrical and spectator entertainment venues)",
        "secondary_maxims": "• Noscitur a sociis (known by its companions)\n• Strictissimi juris (strict construction of tax statutes)",
        "violation_text": "The province ignored the unifying genus of Section 140 LGC, expanding a spectator entertainment tax to cover active swimming and resort facilities.",
        "execution_text": "Doctrine of Ejusdem Generis: Where general words follow particular and specific words, the general words must be confined to things of the same kind (ejusdem generis) as those specified.",
        "statcon_plain": "When a law lists specific examples followed by 'and others', the 'others' must be the exact same type of thing as the examples listed.",
        "statcon_recite": "\"Sir/Ma'am, Pelizloy v. Province of Benguet is the premier modern case illustrating Ejusdem Generis: 'other places of amusement' is confined to the genus of spectator entertainment.\""
    },
    {
        "num": 35,
        "title": "Coca-Cola Bottlers, Phils., Inc. (CCBPI) v. City of Manila and Liberty M. Gomez",
        "citation": "G.R. No. 154491 | November 14, 2008 | 571 SCRA 18 | First Division | Ponente: J. Azcuna",
        "plaintiff": "Coca-Cola Bottlers, Phils., Inc. (Petitioner)",
        "defendant": "City of Manila and Liberty M. Gomez, City Treasurer (Respondents)",
        "court": "Regional Trial Court of Manila (Branch 21) / Court of Appeals",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning double taxation and interpretation of Section 143 of the Local Government Code versus Manila Tax Ordinance No. 7794 and 7807.",
        "facts": "Coca-Cola Bottlers, Phils., Inc. manufactures and sells beverages in the City of Manila. The City of Manila assessed CCBPI under Section 14 of Manila Tax Ordinance No. 7794 as a 'manufacturer' of beverages, and simultaneously assessed CCBPI under Section 21 of the same ordinance as a 'distributor/dealer' of businesses subject to excise tax under the NIRC. CCBPI protested, arguing that under Section 143 of the Local Government Code, a single business enterprise cannot be subjected to double business tax on both manufacturing and distributing when the distribution is merely an incidental part of its manufacturing business.",
        "plain_facts": "The City of Manila taxed Coca-Cola twice on the very same bottles of soda: first as a manufacturer, and second as a distributor. Coca-Cola protested, arguing that making soda and delivering it are part of one single manufacturing business, and the Local Government Code does not allow cities to slap double business taxes on the same revenue. The Supreme Court ruled that double taxation is prohibited where the statute does not expressly authorize it.",
        "issue": "Whether or not the City of Manila can tax a beverage company simultaneously as a manufacturer and as a distributor on the same sales receipts under the Local Government Code.",
        "issue_plain": "Can a city government charge a company double business taxes on the same soft drinks by taxing them once as a maker and again as a seller?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the Local Government Code permits double taxation on the same business activity, testing the Presumption Against Double Taxation (In Dubio Contra Duplicem Taxationem) and strict construction of municipal taxing statutes.\"",
        "answer": "NO. The City of Manila CANNOT subject CCBPI to double taxation. In statutory construction, there is a strong presumption against double taxation unless the statute expressly and unmistakably authorizes it.",
        "answer_plain": "No. Double taxation is heavily frowned upon by law. When a company manufactures soft drinks, selling them is part of manufacturing. A city cannot slice one business into two just to collect double tax.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court held that under the Presumption Against Double Taxation, tax statutes are construed strictly against the taxing power. Since Section 143 of the LGC treats manufacturing and distributing as separate categories, a manufacturer selling its own products cannot be taxed twice on both.\"",
        "legal_basis": [
            ("1. Section 143, Republic Act No. 7160 (Local Government Code):", "Governs local business taxes on manufacturers and wholesalers/distributors."),
            ("2. Presumption Against Double Taxation (In Dubio Contra Duplicem Taxationem):", "Doubts are resolved against the imposition of multiple taxes on the same subject matter for the same purpose."),
            ("3. Strictissimi Juris (of the strictest interpretation) in Local Taxation:", "Municipal corporations have no inherent power of taxation; delegated authority must be exercised strictly within legislative limits.")
        ],
        "legal_basis_plain": "Section 143 LGC, Presumption Against Double Taxation, and Strictissimi Juris in taxation.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 143 of RA 7160, governed by the Presumption Against Double Taxation and Strictissimi Juris (strict construction against the taxing authority).\"",
        "analysis": [
            ("1. Presumption Against Double Taxation:", "Double taxation is obnoxious and condemned in our legal system. It is never presumed, and a statute will not be construed as imposing double taxation unless the legislative intent is expressed in clear and categorical terms."),
            ("2. Incidental Nature of Distribution:", "A manufacturer necessarily sells and distributes what it produces. To tax it as both manufacturer and distributor on the exact same gross sales creates prohibited double taxation."),
            ("3. Strict Interpretation Against Municipal Power:", "Any ambiguity in municipal tax ordinances must be resolved strictly against the city and liberally in favor of the taxpayer.")
        ],
        "analysis_plain": "Selling is part of making goods—you can't be a manufacturer without selling your products. If the city taxes you for making the soda, it cannot tax you again for handing the soda to stores. The Court held that unless Congress says 'tax them twice', the presumption against double taxation blocks the second tax.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied the presumption against double taxation. Statutes granting local taxing powers are strictly construed. The Court held that manufacturing includes distribution, and subjecting both to separate local taxes on the same gross receipts constitutes invalid double taxation.\"",
        "conclusion": "The Supreme Court GRANTED the petition, REVERSED the Court of Appeals, and DECLARED the second tax assessment under Section 21 NULL AND VOID.",
        "conclusion_plain": "Coca-Cola won and the second duplicate tax assessment was struck down.",
        "conclusion_recite": "\"The Supreme Court cancelled the double assessment, reaffirming the statutory presumption against double taxation.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Presumption Against Double Taxation & Strict Construction of Tax Laws",
        "latin_maxims": [
            ("In dubio contra duplicem taxationem (in doubt, rule against double taxation)", "In doubt, against double taxation.", "Tax statutes are never construed as imposing duplicate burdens on the same subject unless explicitly commanded."),
            ("Strictissimi juris (of the strictest interpretation)", "Of the strictest law.", "Grants of taxing power to local government units are strictly construed against the municipality."),
            ("Nemo debet bis vexari pro una et eadem causa (no one should be twice troubled for one and the same cause)", "No one ought to be twice vexed for the same cause.", "A taxpayer cannot be subjected to repetitive taxes for the same commercial enterprise.")
        ],
        "primary_maxim": "In dubio contra duplicem taxationem\n(in doubt, rule against double taxation / statutes are presumed not to authorize duplicate municipal taxes on single business activities)",
        "secondary_maxims": "• Strictissimi juris (strict interpretation of tax laws)\n• Nemo debet bis vexari (no one should be twice burdened for the same cause)",
        "violation_text": "The City of Manila created double taxation by splitting a unified manufacturing business into separate taxable entities without statutory authorization.",
        "execution_text": "Presumption Against Double Taxation: Double taxation is obnoxious to the law; statutes must be construed to prevent double taxation unless the legislative intent to impose it is clear beyond question.",
        "statcon_plain": "Taxes cannot be charged twice on the same money unless the law specifically and unmistakably orders a double tax.",
        "statcon_recite": "\"Sir/Ma'am, Coca-Cola Bottlers v. Gomez is the leading authority on the statutory presumption against double taxation under the Local Government Code.\""
    },
    {
        "num": 36,
        "title": "Jose G. Atienza, Jr. v. Jose L. Villarosa",
        "citation": "G.R. No. 161081 | May 10, 2005 | 458 SCRA 385 | En Banc | Ponente: J. Callejo, Sr.",
        "plaintiff": "Jose G. Atienza, Jr. (Petitioner)",
        "defendant": "Jose L. Villarosa (Respondent)",
        "court": "Regional Trial Court of Occidental Mindoro / Supreme Court En Banc",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning the statutory allocation of administrative and appointing powers between the Provincial Governor and the Vice-Governor under Republic Act No. 7160 (Local Government Code).",
        "facts": "A bitter political conflict erupted in Occidental Mindoro between Governor Jose Villarosa and Vice-Governor Jose Atienza, Jr. over who had the authority to appoint personnel of the Sangguniang Panlalawigan and sign purchase orders and disbursement vouchers for legislative branch expenses. Governor Villarosa insisted that Section 465 of the Local Government Code gives the Provincial Governor supreme administrative authority over all provincial employees and finances. Vice-Governor Atienza countered that Section 466 explicitly designates the Vice-Governor as the presiding officer of the Sangguniang Panlalawigan with the exclusive power to appoint all legislative officials and approve vouchers payable from legislative funds.",
        "plain_facts": "The Governor and Vice-Governor of Occidental Mindoro fought over who had the right to hire employees and sign checks for the provincial legislative board (Sangguniang Panlalawigan). The Governor claimed he runs the entire province, while the Vice-Governor claimed the law gives him control over the legislative board. The Supreme Court harmonized all sections of the Local Government Code, ruling that the Vice-Governor has sole power to hire legislative staff and sign legislative expenses, while the Governor controls the executive branch.",
        "issue": "Whether or not the Vice-Governor, as presiding officer of the Sangguniang Panlalawigan, has the statutory authority to appoint personnel of the legislative council and approve disbursement vouchers for legislative operations, to the exclusion of the Provincial Governor.",
        "issue_plain": "Does the Vice-Governor or the Governor have the legal power to hire staff and sign checks for the provincial legislative board?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the appointing and spending powers over the Sangguniang Panlalawigan belong to the Vice-Governor or the Governor under RA 7160, testing the canon of Construing a Statute as a Whole (Ut Res Magis Valeat Quam Pereat / Ex Antecedentibus Et Consequentibus).\"",
        "answer": "The VICE-GOVERNOR has the exclusive authority to appoint all officials and employees of the Sangguniang Panlalawigan and to sign purchase orders and vouchers payable from legislative appropriations. The Local Government Code must be construed as a whole to harmonize executive and legislative powers.",
        "answer_plain": "The Vice-Governor. When you read the whole Local Government Code together, it is clear that the Governor heads the Executive branch and the Vice-Governor heads the Legislative branch. The Governor cannot meddle in legislative hiring and checks.",
        "answer_recite": "\"Sir/Ma'am, the Supreme Court held that under Ut res magis valeat quam pereat (that the thing may have effect rather than perish) and construing the Local Government Code as an integrated whole, Section 466 gives the Vice-Governor exclusive authority over legislative staff and vouchers, while the Governor's powers under Section 465 are confined to executive personnel.\"",
        "legal_basis": [
            ("1. Sections 465, 466, and 468, Republic Act No. 7160 (Local Government Code of 1991):", "Allocation of powers between the Provincial Governor (executive) and Vice-Governor (presiding officer of the sanggunian)."),
            ("2. Ut Res Magis Valeat Quam Pereat (that the thing may rather have effect than perish):", "All provisions of the Local Government Code must be harmonized so that each section operates with full vitality."),
            ("3. Ex Antecedentibus Et Consequentibus Fit Optima Interpretatio (the best interpretation is made from the context):", "Statutory clauses must be interpreted in connection with preceding and succeeding clauses.")
        ],
        "legal_basis_plain": "Sections 465 & 466 RA 7160, Ut Res Magis Valeat Quam Pereat, and Ex Antecedentibus Et Consequentibus.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Sections 465 and 466 of RA 7160, construed under Ut res magis valeat quam pereat (that the statute may have effect rather than perish) and Ex antecedentibus et consequentibus fit optima interpretatio.\"",
        "analysis": [
            ("1. Construction as an Integrated Whole:", "A statute must be read in its entirety. Section 465 cannot be read in isolation to swallow up Section 466; both sections must be harmonized to reflect the separation of executive and legislative powers at the local government level."),
            ("2. Presiding Officer's Inherent Administrative Prerogative:", "The Vice-Governor is the head of the legislative body. Giving the Governor power over legislative personnel would destroy legislative independence and subvert local checks and balances."),
            ("3. Specific vs. General Allocation:", "Section 466 specifically assigns legislative appointments and sanggunian voucher approvals to the Vice-Governor, acting as an exception to the Governor's general executive authority under Section 465.")
        ],
        "analysis_plain": "You cannot read one section of a law and ignore the rest. If the Governor controlled the legislative employees, the legislative council would lose its independence. By reading the whole statute together, the Court gave full meaning to both the Governor's executive role and the Vice-Governor's legislative role.",
        "analysis_recite": "\"Sir/Ma'am, the Court harmonized the entire Local Government Code. Under Ut Res Magis Valeat Quam Pereat, the statute maintains local separation of powers: the Governor administers executive offices, while the Vice-Governor exercises exclusive appointing and fiscal authority over the Sangguniang Panlalawigan.\"",
        "conclusion": "The Supreme Court PARTIALLY GRANTED the petition, DECLARING that the Vice-Governor has the exclusive power to appoint Sangguniang Panlalawigan personnel and sign legislative purchase orders and disbursement vouchers.",
        "conclusion_plain": "The Vice-Governor was affirmed as the exclusive authority over legislative staff and vouchers.",
        "conclusion_recite": "\"The Supreme Court upheld the Vice-Governor's exclusive authority over legislative personnel and expenditures through harmonious statutory construction.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Statute Construed as a Whole (Ut Res Magis Valeat Quam Pereat)",
        "latin_maxims": [
            ("Ut res magis valeat quam pereat (that the thing may rather have effect than perish)", "That the thing may have effect rather than perish.", "All parts of the Local Government Code must be construed together to give full meaning and operation to every section."),
            ("Ex antecedentibus et consequentibus fit optima interpretatio (the best interpretation is made from what precedes and what follows)", "The best interpretation arises from comparing preceding and following clauses.", "The Governor's general powers in Section 465 must be read alongside the Vice-Governor's specific powers in Section 466."),
            ("Generalia specialibus non derogant (general things do not derogate from special things)", "General provisions do not override specific provisions.", "General executive powers of the Governor yield to the specific legislative appointing powers of the Vice-Governor.")
        ],
        "primary_maxim": "Ut res magis valeat quam pereat\n(that the thing may have effect rather than perish / harmonizing executive and legislative powers across the Local Government Code)",
        "secondary_maxims": "• Ex antecedentibus et consequentibus fit optima interpretatio (best interpretation from the whole context)\n• Generalia specialibus non derogant (general provisions yield to specific ones)",
        "violation_text": "The Governor isolated Section 465 from the rest of the Local Government Code, attempting to usurp powers specifically granted to the Vice-Governor under Section 466.",
        "execution_text": "Doctrine of Harmonious Whole: A statute must be construed as a harmonious whole; no single provision should be isolated to defeat or render another provision superfluous or meaningless.",
        "statcon_plain": "Every section of a code must be read together like gears in a clock so that every part works smoothly without jamming.",
        "statcon_recite": "\"Sir/Ma'am, Atienza v. Villarosa is the textbook case on construing a statute as a whole (Ut res magis valeat quam pereat), harmonizing executive and legislative powers under the Local Government Code.\""
    },
    {
        "num": 37,
        "title": "Commission on Human Rights Employees' Association (CHREA) v. Commission on Human Rights",
        "citation": "G.R. No. 155336 | November 25, 2004 | 444 SCRA 300 | First Division | Ponente: J. Ynares-Santiago",
        "plaintiff": "Commission on Human Rights Employees' Association (CHREA) (Petitioner)",
        "defendant": "Commission on Human Rights (CHR) (Respondent)",
        "court": "Civil Service Commission / Court of Appeals",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning the validity of CHR Resolution No. A98-047 upgrading and reclassifying rank-and-file plantilla positions without approval of the Department of Budget and Management (DBM).",
        "facts": "The Commission on Human Rights (CHR) issued Resolution No. A98-047 adopting an internal 'Upgrading and Reclassification Scheme' that elevated certain high-level legal and executive positions while collapsing and leaving behind lower rank-and-file plantilla positions. CHREA (the employees' union) protested, arguing that the upgrading violated Republic Act No. 6758 (The Compensation and Position Classification Act of 1989 / Salary Standardization Law) and lacked the mandatory approval of the DBM and Civil Service Commission. CHR claimed that as an independent constitutional office under Article XIII, Section 17 of the 1987 Constitution, it possessed full fiscal autonomy to reclassify positions and fix salaries without DBM interference.",
        "plain_facts": "The Commission on Human Rights promoted its top bosses and lawyers using an internal reorganization plan, leaving the rank-and-file workers behind. The employees' union objected because the plan was never approved by the Department of Budget and Management (DBM) or Civil Service Commission as required by the Salary Standardization Law. CHR claimed it is an independent body that can do whatever it wants with its salaries. The Supreme Court ruled that CHR is not a constitutional commission with full fiscal autonomy and must strictly obey the Salary Standardization Law.",
        "issue": "Whether or not the Commission on Human Rights (CHR) has the statutory and constitutional authority to reclassify and upgrade positions and salaries without the approval of the DBM under R.A. No. 6758.",
        "issue_plain": "Can the Commission on Human Rights raise salaries and change job titles without DBM approval by claiming constitutional independence?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the CHR is exempt from the Compensation and Position Classification Act (RA 6758), testing the canon of Expressio Unius Est Exclusio Alterius (the express mention of one thing is the exclusion of another) and the boundaries of administrative rule-making.\"",
        "answer": "NO. CHR is NOT exempt from R.A. No. 6758 and CANNOT upgrade positions without DBM approval. CHR is an independent constitutional office, but it is NOT one of the three Constitutional Commissions granted fiscal autonomy under the Constitution.",
        "answer_plain": "No. The Constitution grants fiscal autonomy only to the CSC, COMELEC, and COA. Because CHR is not on that list, Expressio Unius excludes it. CHR must follow the Salary Standardization Law and get DBM approval.",
        "answer_recite": "\"No, Sir/Ma'am. Under Expressio unius est exclusio alterius (the express mention of one thing is the exclusion of another), the constitutional grant of fiscal autonomy is strictly limited to the three Constitutional Commissions (CSC, COMELEC, COA). CHR must comply with RA 6758 and obtain DBM approval for any position upgrading.\"",
        "legal_basis": [
            ("1. Republic Act No. 6758 (Salary Standardization Law):", "Mandates unified position classification and compensation system across all government agencies administered by DBM."),
            ("2. Article IX-A, Section 5, 1987 Constitution:", "Confers fiscal autonomy specifically on the three Constitutional Commissions (CSC, COMELEC, COA)."),
            ("3. Expressio Unius Est Exclusio Alterius (the express mention of one thing is the exclusion of another):", "The explicit enumeration of entities possessing fiscal autonomy excludes all unlisted agencies.")
        ],
        "legal_basis_plain": "RA 6758, Article IX-A Sec 5 Constitution, and Expressio Unius Est Exclusio Alterius.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is RA 6758 and Article IX-A, Section 5 of the Constitution, governed by Expressio unius est exclusio alterius (the express mention of one is the exclusion of another).\"",
        "analysis": [
            ("1. Constitutional Scope of Fiscal Autonomy:", "The 1987 Constitution explicitly named the Civil Service Commission, the Commission on Elections, and the Commission on Audit as Constitutional Commissions with fiscal autonomy. CHR is created under Article XIII as an independent office, not a Constitutional Commission."),
            ("2. Application of Expressio Unius:", "Where the Constitution and the law expressly enumerate the specific bodies endowed with fiscal autonomy and exemption from DBM standardization, all other offices are excluded under the doctrine of expressio unius."),
            ("3. Subordination of Administrative Regulations to Statutes:", "An administrative agency cannot expand its powers or create salary schemes that violate the mandatory provisions of RA 6758.")
        ],
        "analysis_plain": "The Constitution specifically lists the three commissions that have financial independence: Civil Service, Elections, and Audit. CHR is not on that list. Under Expressio Unius, when the law makes a specific list, what is left off the list is excluded. Therefore, CHR must obey the salary law.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied Expressio Unius. The Constitution specifically grants fiscal autonomy only to the three Constitutional Commissions in Article IX. CHR cannot claim fiscal autonomy by implication, and its administrative upgrading without DBM approval was ultra vires.\"",
        "conclusion": "The Supreme Court GRANTED the petition, ANNULLED CHR Resolution No. A98-047, and DECLARED the reclassification scheme void for lack of DBM approval.",
        "conclusion_plain": "The union won; the salary upgrading scheme was declared void and illegal.",
        "conclusion_recite": "\"The Supreme Court struck down the CHR reclassification scheme for violating RA 6758 and the principle of Expressio Unius.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Expressio Unius Est Exclusio Alterius & Administrative Agency Limits",
        "latin_maxims": [
            ("Expressio unius est exclusio alterius (the express mention of one thing is the exclusion of another)", "The express mention of one thing implies the exclusion of others.", "The express constitutional grant of fiscal autonomy to CSC, COMELEC, and COA excludes CHR."),
            ("Potestas delegata non delegari potest (a delegated power cannot be delegated)", "Delegated power cannot be further delegated.", "Administrative agencies cannot usurp legislative salary-fixing authority."),
            ("Optima statuti interpretatrix est ipsum statutum (the best interpreter of a statute is the statute itself)", "The best interpreter of a statute is the statute itself.", "The clear text of RA 6758 establishes universal compensation control across all non-autonomous offices.")
        ],
        "primary_maxim": "Expressio unius est exclusio alterius\n(the express mention of one thing is the exclusion of another / constitutional enumeration of fiscally autonomous bodies excludes CHR)",
        "secondary_maxims": "• Optima statuti interpretatrix est ipsum statutum (the statute itself is its best interpreter)\n• Potestas delegata non delegari potest (delegated power limits)",
        "violation_text": "CHR attempted to arrogate constitutional fiscal autonomy by implication, violating the explicit enumeration in the Constitution and RA 6758.",
        "execution_text": "Doctrine of Expressio Unius: When the Constitution or a statute expressly enumerates the subjects to which a privilege applies, it is an unmistakable indication that all unmentioned subjects are excluded.",
        "statcon_plain": "If the Constitution names three specific commissions that have total budget freedom, other agencies cannot pretend they are included.",
        "statcon_recite": "\"Sir/Ma'am, CHREA v. CHR demonstrates Expressio unius est exclusio alterius: the constitutional enumeration of fiscally autonomous commissions excludes all other independent bodies.\""
    },
    {
        "num": 38,
        "title": "Sterling Selections Corporation v. Laguna Lake Development Authority (LLDA)",
        "citation": "G.R. No. 171427 | March 30, 2011 | 646 SCRA 715 | Third Division | Ponente: J. Peralta",
        "plaintiff": "Sterling Selections Corporation (Petitioner)",
        "defendant": "Laguna Lake Development Authority (LLDA) (Respondent)",
        "court": "Court of Appeals / Supreme Court",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning the regulatory and police power of LLDA to require clearance and penalize pollution under Republic Act No. 4850.",
        "facts": "Sterling Selections Corporation operates a manufacturing facility in Novaliches, Quezon City, producing handicraft and metal gifts, discharging industrial wastewater into a drainage that eventually leads to the Laguna de Bay basin. The Laguna Lake Development Authority (LLDA) inspected the factory, found unpermitted wastewater discharge, and issued an Order of Closure and imposed administrative fines pursuant to Republic Act No. 4850, as amended by P.D. No. 813. Sterling argued that LLDA had no territorial jurisdiction over its factory because Quezon City is not located directly on the shores of Laguna Lake, and contended that LLDA's charter should be strictly construed to cover only lakeshore municipalities.",
        "plain_facts": "A handicraft factory in Quezon City was pouring industrial waste into drains that flow into river tributaries leading to Laguna Lake. The Laguna Lake Development Authority (LLDA) shut down the factory and fined them. The factory sued, claiming LLDA only has authority over towns physically bordering the lake, not Quezon City. The Supreme Court ruled that LLDA's power covers the entire watershed and all tributaries feeding the lake, because environmental laws must be interpreted broadly to protect the water basin.",
        "issue": "Whether or not the regulatory and police powers of the LLDA under R.A. No. 4850 extend to industrial establishments located in river basins and tributaries outside direct lakeshore municipalities.",
        "issue_plain": "Does the Laguna Lake Authority have the legal power to shut down a polluting factory in Quezon City if the factory's dirty water drains into rivers that flow into Laguna Lake?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the territorial jurisdiction of the LLDA under RA 4850 covers the entire watershed basin, testing the canon of Liberal Construction of Environmental and Police Power Statutes (Salus Populi Est Suprema Lex / Ut Res Magis Valeat Quam Pereat).\"",
        "answer": "YES. LLDA's authority EXTENDS to all industrial establishments within the entire Laguna de Bay watershed basin, including tributaries in Quezon City. Environmental statutes enacted under police power are liberally construed to effectuate resource conservation.",
        "answer_plain": "Yes. Pollution dumped into a river in Quezon City flows directly into Laguna Lake. To protect the lake, the law gave LLDA authority over the entire watershed basin, not just the water's edge. Police power laws for the environment are interpreted broadly.",
        "answer_recite": "\"Yes, Sir/Ma'am. The Supreme Court held that under Salus populi est suprema lex (the welfare of the people is the supreme law) and purposive statutory construction, RA 4850 gives LLDA comprehensive jurisdiction over the entire Laguna de Bay watershed basin to protect the environmental integrity of the lake.\"",
        "legal_basis": [
            ("1. Republic Act No. 4850 (as amended by P.D. No. 813 and E.O. No. 927):", "Charter of the Laguna Lake Development Authority granting regulatory, licensing, and water quality control powers."),
            ("2. Salus Populi Est Suprema Lex (the welfare of the people is the supreme law):", "Environmental protection statutes enacted pursuant to the State's police power are given expansive, efficacious interpretation."),
            ("3. Ut Res Magis Valeat Quam Pereat (that the thing may rather have effect than perish):", "Statutes creating regulatory agencies must be interpreted to make their environmental mandate effective rather than toothless.")
        ],
        "legal_basis_plain": "RA 4850, PD 813, Salus Populi Est Suprema Lex, and Ut Res Magis Valeat Quam Pereat.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is RA 4850 as amended, construed under Salus populi est suprema lex (the welfare of the people is supreme law) and Ut res magis valeat quam pereat (construction to preserve statutory effectiveness).\"",
        "analysis": [
            ("1. Ecological and Hydrological Reality:", "Laguna de Bay is a hydrological basin fed by over 21 river tributaries. Regulating only the shoreline while ignoring upstream polluters would render the law futile and defeat the statutory mandate."),
            ("2. Broad Police Power Grant:", "Executive Order No. 927 explicitly defined the Laguna de Bay Region to encompass the surrounding drainage basins and catchment areas, including parts of Metro Manila."),
            ("3. Purposive Interpretation of Environmental Laws:", "Courts must construe environmental protection charters with sufficient breadth to enable administrative agencies to fulfill their ecological mandates.")
        ],
        "analysis_plain": "Water flows downhill. If factories upstream could dump poison into rivers without LLDA control, the lake would be ruined within months. The Court ruled that the law must be interpreted to match the reality of nature: you cannot protect a lake without protecting the rivers that feed it.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied purposive ecological construction. Under Ut Res Magis Valeat Quam Pereat, statutory charters protecting public resources must be interpreted to cover the entire ecological watershed; otherwise, upstream pollution would defeat the entire purpose of RA 4850.\"",
        "conclusion": "The Supreme Court DENIED the petition, AFFIRMED the closure order and administrative fines against Sterling Selections Corporation, and UPHELD LLDA's watershed jurisdiction.",
        "conclusion_plain": "The factory lost; LLDA's shutdown order and pollution fines were affirmed.",
        "conclusion_recite": "\"The Supreme Court affirmed LLDA's jurisdiction over the entire watershed basin under liberal construction of environmental police powers.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Liberal Construction of Environmental & Police Power Statutes",
        "latin_maxims": [
            ("Salus populi est suprema lex (the welfare of the people is the supreme law)", "The welfare of the people is the supreme law.", "Statutes protecting public health and environmental water resources are granted broad, effective construction."),
            ("Ut res magis valeat quam pereat (that the thing may rather have effect than perish)", "That the thing may have effect rather than perish.", "Environmental protection statutes must be construed to make resource preservation effective rather than futile."),
            ("Sic utere tuo ut alienum non laedas (use your own property so as not to injure that of another)", "Use your property so as not to harm others.", "Industrial property owners cannot claim freedom from regulation while discharging toxic effluent.")
        ],
        "primary_maxim": "Salus populi est suprema lex\n(the welfare of the people is the supreme law / broad interpretation of environmental police powers over watershed basins)",
        "secondary_maxims": "• Ut res magis valeat quam pereat (construction to preserve statutory effectiveness)\n• Sic utere tuo ut alienum non laedas (use property without harming others)",
        "violation_text": "The factory attempted to construct an artificial, geographic loophole to bypass environmental regulation and discharge industrial wastewater into the public water basin.",
        "execution_text": "Ecological Police Power Construction: Environmental statutes are construed liberally to encompass entire natural drainage systems necessary to achieve pollution control.",
        "statcon_plain": "Environmental laws are interpreted broadly so that polluters cannot find clever geographic excuses to poison public waters.",
        "statcon_recite": "\"Sir/Ma'am, Sterling Selections v. LLDA shows that police power and environmental statutes are interpreted broadly under Salus populi est suprema lex to protect natural watersheds.\""
    },
    {
        "num": 39,
        "title": "Commission on Audit of the Province of Cebu v. Province of Cebu",
        "citation": "G.R. No. 141386 | November 29, 2001 | 371 SCRA 126 | En Banc | Ponente: J. Puno",
        "plaintiff": "Commission on Audit of the Province of Cebu (Petitioner)",
        "defendant": "Province of Cebu (Respondent)",
        "court": "Commission on Audit / Supreme Court En Banc",
        "nature": "Petition for Review on Certiorari under Rule 64 assailing COA disallowance of salaries paid to provincial teachers and clerks charged against the Special Education Fund (SEF) under Section 272 of the Local Government Code.",
        "facts": "The Province of Cebu, through its Provincial School Board, hired extension teachers, physical education instructors, and clerical aides to handle public elementary and high school classes, charging their salaries against the provincial Special Education Fund (SEF). The COA Provincial Auditor disallowed the disbursements, contending that under Section 272 of Republic Act No. 7160 (Local Government Code) and Republic Act No. 5447 (Special Education Fund Act), the SEF can be spent ONLY for the 'establishment and maintenance of extension classes, sports activities, and school facilities,' and cannot be used to pay salaries of non-extension teachers and clerks, invoking Expressio Unius.",
        "plain_facts": "The Province of Cebu used its Special Education Fund (a special tax collected for schools) to hire extra teachers, sports coaches, and school clerks. The COA auditor blocked the payroll, arguing that the Local Government Code strictly lists what the education fund can be spent on (building classrooms, sports, and extension classes) and does not list regular school clerks or permanent teachers. The Supreme Court ruled that under Expressio Unius, the specific statutory list of authorized expenses is exclusive, but actual extension teachers hired for extension classes were legally payable.",
        "issue": "Whether or not the Special Education Fund (SEF) under Section 272 of the Local Government Code can be used to pay the salaries of regular school teachers, clerical aides, and non-extension personnel.",
        "issue_plain": "Can local governments spend the Special Education Fund on salaries of regular school clerks and non-extension personnel when the law specifies only extension classes, sports, and facilities?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether Section 272 of RA 7160 permits the use of the Special Education Fund for expenses outside its statutory enumeration, testing the canon Expressio Unius Est Exclusio Alterius (the express mention of one thing is the exclusion of another).\"",
        "answer": "NO as to regular teachers and clerical personnel; YES as to genuine extension teachers. Under Expressio Unius Est Exclusio Alterius, the statutory enumeration in Section 272 of the LGC is EXCLUSIVE, and the SEF cannot be diverted to unlisted administrative expenses.",
        "answer_plain": "No for office clerks and regular staff; yes for teachers who actually run extension classes. Because the law specifically lists what the Special Education Fund can pay for, everything not on the list is excluded under Expressio Unius.",
        "answer_recite": "\"Sir/Ma'am, the Supreme Court held that under Expressio unius est exclusio alterius (the express mention of one thing is the exclusion of another), the statutory enumeration of allowable SEF expenditures in Section 272 of the LGC is exclusive. The SEF can only pay for extension teachers, sports, and school facilities, not regular administrative clerks.\"",
        "legal_basis": [
            ("1. Section 272, Republic Act No. 7160 (Local Government Code of 1991):", "Specifically enumerates authorized uses of the Special Education Fund (operation and maintenance of extension classes, sports, construction of facilities)."),
            ("2. Republic Act No. 5447 (Special Education Fund Act):", "Original enabling law establishing the special education fund."),
            ("3. Expressio Unius Est Exclusio Alterius (the express mention of one thing is the exclusion of another):", "The explicit statutory specification of authorized expense items excludes all unlisted expenses.")
        ],
        "legal_basis_plain": "Section 272 RA 7160, RA 5447, and Expressio Unius Est Exclusio Alterius.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 272 of RA 7160, governed by Expressio unius est exclusio alterius (the express mention of one thing is the exclusion of another).\"",
        "analysis": [
            ("1. Nature of the Special Education Fund:", "The SEF is a dedicated trust fund created from an additional 1% real property tax, strictly earmarked for specific statutory educational purposes."),
            ("2. Exclusivity of Statutory Enumeration:", "Section 272 explicitly specifies: (a) extension classes; (b) facilities construction and repair; (c) educational research; (d) purchase of books; and (e) sports development. Under Expressio Unius, salaries of regular teachers and clerical personnel are excluded."),
            ("3. Validity of Extension Teachers:", "Salaries of extension teachers hired precisely to handle newly opened extension classes fall squarely within 'operation and maintenance of extension classes' and are validly chargeable against the SEF.")
        ],
        "analysis_plain": "The Special Education Fund is special money collected for specific educational needs. When a statute gives a precise checklist of 5 things you can buy with special funds, you cannot add a 6th thing like office clerks. However, teachers hired to teach extension classes fit the express category and are allowed.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied Expressio Unius. Since Section 272 explicitly enumerates the allowable uses of the SEF, unlisted items like clerical salaries are excluded. The Court allowed salaries for genuine extension teachers but disallowed regular non-extension personnel.\"",
        "conclusion": "The Supreme Court AFFIRMED WITH MODIFICATION the COA decision, SUSTAINING the disallowance of salaries for clerks and non-extension personnel, but ALLOWING the disbursements for genuine extension class teachers.",
        "conclusion_plain": "The salaries of extension teachers were approved, but clerical and regular salaries were disallowed.",
        "conclusion_recite": "\"The Supreme Court modified the disallowance, upholding Expressio Unius to restrict SEF usage strictly to statutory categories.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Expressio Unius Est Exclusio Alterius (Special Funds)",
        "latin_maxims": [
            ("Expressio unius est exclusio alterius (the express mention of one thing is the exclusion of another)", "The express mention of one thing implies the exclusion of others.", "The statutory listing of permitted SEF disbursements excludes unlisted administrative expenditures."),
            ("Expressum facit cessare tacitum (what is expressed puts an end to that which is implied)", "That which is expressed supersedes that which is implied.", "The explicit statutory enumeration of fund purposes leaves no room for implied spending categories."),
            ("Dura lex, sed lex (the law is harsh, but it is the law)", "The law is harsh, but it is the law.", "Statutory fiscal restrictions on trust funds must be strictly followed regardless of local convenience.")
        ],
        "primary_maxim": "Expressio unius est exclusio alterius\n(the express mention of one thing is the exclusion of another / statutory list of allowable Special Education Fund expenses is exclusive)",
        "secondary_maxims": "• Expressum facit cessare tacitum (what is expressed ends what is implied)\n• Dura lex sed lex (fiscal fund restrictions are strictly enforced)",
        "violation_text": "The local government attempted to divert earmarked special education trust funds to general administrative salaries not enumerated in the statute.",
        "execution_text": "Exclusivity of Statutory Enumeration for Special Funds: When a statute creates a special trust fund and enumerates allowable disbursements, the enumeration is exclusive under Expressio Unius.",
        "statcon_plain": "When the law gives a specific shopping list for spending special tax money, you cannot buy items that are not on the list.",
        "statcon_recite": "\"Sir/Ma'am, COA v. Province of Cebu establishes that statutory enumerations of special fund disbursements are exclusive under Expressio unius est exclusio alterius.\""
    },
    {
        "num": 40,
        "title": "Colgate-Palmolive Philippines, Inc. v. Pedro M. Gimenez",
        "citation": "G.R. No. L-14787 | January 28, 1961 | 1 SCRA 267 | En Banc | Ponente: J. Gutierrez David",
        "plaintiff": "Colgate-Palmolive Philippines, Inc. (Petitioner)",
        "defendant": "Pedro M. Gimenez, as Auditor General (Respondent)",
        "court": "Auditor General / Supreme Court En Banc",
        "nature": "Petition for Review of Auditor General ruling denying refund of 17% foreign exchange margin levy on imported Irish moss and dental cream stabilizers under Republic Act No. 601.",
        "facts": "Colgate-Palmolive imported 'Irish moss extract' and sodium carboxymethylcellulose to be used as stabilizers and emulsifiers in manufacturing dental cream (toothpaste). The Central Bank collected the 17% special foreign exchange tax under Republic Act No. 601. Colgate claimed a tax refund under Section 2 of RA 601, which exempts foreign exchange used for importation of 'stabilizers and flavors... for food, and medical and hospital supplies.' The Auditor General denied the refund, contending that dental cream is not a food or medicine, and that under Ejusdem Generis, 'stabilizers' must be restricted strictly to food stabilizers.",
        "plain_facts": "Colgate imported stabilizers to make toothpaste and asked for a tax refund under a law that exempts foreign exchange for 'stabilizers and flavors... for food, and medical and hospital supplies.' The government auditor refused the refund, claiming the word 'stabilizers' only applies to food stabilizers, not toothpaste stabilizers. The Supreme Court ruled in favor of Colgate, holding that the general word 'stabilizers' stood alone without the modifying phrase 'for food', and Ejusdem Generis cannot be used to restrict a word that the legislature deliberately left broad.",
        "issue": "Whether or not the statutory exemption for 'stabilizers and flavors' in Section 2 of R.A. No. 601 includes stabilizers used for dental cream, testing the limits of Ejusdem Generis and Noscitur a Sociis.",
        "issue_plain": "Does the tax exemption for 'stabilizers and flavors' include toothpaste stabilizers, or is it limited strictly to food stabilizers?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the term 'stabilizers' in RA 601 is limited to food stabilizers or covers toothpaste stabilizers, testing the proper application and limits of Ejusdem Generis (of the same kind) and Verba Legis.\"",
        "answer": "YES. The imported stabilizers used for dental cream ARE EXEMPT from the foreign exchange levy. Ejusdem Generis does NOT apply because the word 'stabilizers' is preceded by no specific enumeration of food items.",
        "answer_plain": "Yes. Toothpaste stabilizers are exempt. Ejusdem Generis only works when there is a specific list of items followed by general words. Here, Congress wrote 'stabilizers and flavors' as independent categories, so the court cannot invent a restriction.",
        "answer_recite": "\"Yes, Sir/Ma'am. The Supreme Court held that the rule of Ejusdem Generis (of the same kind) applies ONLY when specific words are followed by general words. In Section 2 of RA 601, 'stabilizers' is a general term standing alone; hence, under Verba Legis and Ubi Lex Non Distinguit, it covers all stabilizers, including those for dental cream.\"",
        "legal_basis": [
            ("1. Section 2, Republic Act No. 601 (Foreign Exchange Tax Act):", "Provides foreign exchange tax exemption for 'stabilizers and flavors, cattle, medical and hospital supplies'."),
            ("2. Limits of Ejusdem Generis (of the same kind):", "Ejusdem generis requires an enumeration of specific things followed by a general term. It does not apply where general words precede or stand independently."),
            ("3. Ubi Lex Non Distinguit, Nec Nos Distinguere Debemus (where the law does not distinguish, we should not distinguish):", "Since the statute said 'stabilizers' without qualification, courts cannot distinguish between food stabilizers and toothpaste stabilizers.")
        ],
        "legal_basis_plain": "Section 2 RA 601, Limits of Ejusdem Generis, and Ubi Lex Non Distinguit.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 2 of RA 601, guided by the rule on the Limits of Ejusdem Generis and Ubi lex non distinguit nec nos distinguere debemus (where the law does not distinguish, we must not distinguish).\"",
        "analysis": [
            ("1. Inapplicability of Ejusdem Generis:", "For ejusdem generis to apply, there must be: (1) an enumeration of specific words belonging to a class; (2) followed by general words; and (3) no contrary legislative intent. Here, 'stabilizers' was not preceded by specific food items."),
            ("2. Syntax and Punctuation:", "The statute separated 'flavors' and other items. The phrase 'for food' modified only certain categories, not the independent term 'stabilizers'."),
            ("3. Plain Meaning Rule:", "When the statutory term is broad and unqualified, it must be given its ordinary commercial and technical meaning encompassing all chemical stabilizers.")
        ],
        "analysis_plain": "The government auditor tried to use Ejusdem Generis backwards. Ejusdem Generis only applies when a law lists specific examples and ends with general words. Here, the word 'stabilizers' was a standalone category. Where the law does not distinguish what kind of stabilizer, the auditor cannot add his own restriction.",
        "analysis_recite": "\"Sir/Ma'am, the Court explained the limits of Ejusdem Generis. Because there was no specific list preceding 'stabilizers', the general term must be given its full natural scope under Ubi Lex Non Distinguit. The Court ordered the tax refund.\"",
        "conclusion": "The Supreme Court REVERSED the Auditor General's decision and ORDERED the refund of the 17% foreign exchange tax paid by Colgate-Palmolive.",
        "conclusion_plain": "Colgate won and the government was ordered to refund the foreign exchange taxes.",
        "conclusion_recite": "\"The Supreme Court reversed the denial and ordered the tax refund, clarifying the strict prerequisites for applying Ejusdem Generis.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Inapplicability & Prerequisites of Ejusdem Generis",
        "latin_maxims": [
            ("Ejusdem generis (of the same kind or class)", "Of the same kind.", "The maxim applies only when specific enumerations are followed by general terms—it cannot be used to restrict standalone general words."),
            ("Ubi lex non distinguit, nec nos distinguere debemus (where the law does not distinguish, we should not distinguish)", "Where the law makes no distinction, we must make none.", "The statute made no distinction between food stabilizers and toothpaste stabilizers."),
            ("Verba legis non est recedendum (from the words of the statute there should be no departure)", "From the words of the statute there must be no departure.", "General statutory words must be given their direct literal effect.")
        ],
        "primary_maxim": "Ejusdem generis\n(of the same kind or class / the maxim requires specific words followed by general words and cannot restrict standalone general terms)",
        "secondary_maxims": "• Ubi lex non distinguit (where the law does not distinguish)\n• Verba legis non est recedendum (from the words of the statute no departure)",
        "violation_text": "The Auditor General misapplied Ejusdem Generis to restrict a standalone general statutory term that was not preceded by specific enumerations.",
        "execution_text": "Prerequisites of Ejusdem Generis: The doctrine of ejusdem generis cannot be applied unless there is an actual enumeration of specific things followed by general terms.",
        "statcon_plain": "You cannot use the Ejusdem Generis rule to shrink a broad word unless the law actually started with a list of specific examples.",
        "statcon_recite": "\"Sir/Ma'am, Colgate-Palmolive v. Gimenez is the leading authority defining the exact prerequisites of Ejusdem Generis: it cannot restrict a standalone general word.\""
    },
    {
        "num": 41,
        "title": "Roman Catholic Archbishop of Manila v. Social Security Commission",
        "citation": "G.R. No. L-15045 | January 20, 1961 | 1 SCRA 10 | En Banc | Ponente: J. Gutierrez David",
        "plaintiff": "Roman Catholic Archbishop of Manila (Petitioner)",
        "defendant": "Social Security Commission (Respondent)",
        "court": "Social Security Commission / Supreme Court En Banc",
        "nature": "Petition for Review of Social Security Commission Resolution denying exemption of religious and charitable institutions from compulsory coverage under Republic Act No. 1161 (Social Security Act).",
        "facts": "The Roman Catholic Archbishop of Manila requested an exemption from compulsory coverage under the Social Security Act (R.A. No. 1161, as amended) for all Catholic religious, charitable, and educational institutions, and their lay personnel. The Archbishop argued that Section 8(j) of the SSS Act, which defines 'employment' as 'any service performed by an employee for his employer,' should be restricted through Ejusdem Generis and Noscitur a Sociis to purely commercial, industrial, and profit-making enterprises. The Social Security Commission denied the exemption, holding that the law makes no exception for non-profit or religious institutions.",
        "plain_facts": "The Catholic Church asked the Social Security Commission to exempt all religious, charitable, and Catholic school lay employees from mandatory SSS contributions. The Church argued that SSS was meant only for commercial, money-making businesses, and invoked the rules of Ejusdem Generis and Noscitur a Sociis. The Supreme Court ruled that the SSS Act covers all employers and employees regardless of whether the organization makes a profit or is a religious institution, because social welfare laws protect all workers.",
        "issue": "Whether or not religious, charitable, and non-profit institutions are exempt from compulsory SSS coverage under Republic Act No. 1161 through the application of Ejusdem Generis or Noscitur a Sociis.",
        "issue_plain": "Is the Catholic Church exempt from paying SSS contributions for its lay staff on the ground that it is a religious non-profit organization?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether religious and non-profit institutions are excluded from compulsory SSS coverage, testing the proper scope of Ejusdem Generis (of the same kind), Noscitur a Sociis (known by its companions), and Ubi Lex Non Distinguit.\"",
        "answer": "NO. Religious and non-profit institutions are NOT EXEMPT from compulsory SSS coverage. The statutory definition of 'employer' and 'employment' under R.A. No. 1161 is all-inclusive and admits of no implied religious exemptions.",
        "answer_plain": "No. The law covers all employment without exception. Lay workers in churches and religious schools need disability and retirement protection just like workers in commercial factories. Where the law does not make an exception, courts cannot make one.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court held that under Ubi lex non distinguit nec nos distinguere debemus (where the law does not distinguish, we should not distinguish), the SSS Act applies to all employers and employees. The rules of Ejusdem Generis and Noscitur a Sociis cannot be applied to defeat the universal, protective intent of social legislation.\"",
        "legal_basis": [
            ("1. Section 8(c) and 8(j), Republic Act No. 1161 (Social Security Act):", "Defines 'employer' as any person or entity carrying on any enterprise, and 'employment' as any service performed for an employer."),
            ("2. Ubi Lex Non Distinguit, Nec Nos Distinguere Debemus (where the law does not distinguish, we should not distinguish):", "Since Section 8 does not distinguish between profit and non-profit employers, courts cannot distinguish."),
            ("3. Expressio Unius Est Exclusio Alterius (the express mention of one thing is the exclusion of another):", "Section 8(j) contains an express list of exempt services (e.g., domestic service, government employment), which does not include religious institutions.")
        ],
        "legal_basis_plain": "Section 8 RA 1161, Ubi Lex Non Distinguit, and Expressio Unius Est Exclusio Alterius.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 8 of RA 1161, governed by Ubi lex non distinguit nec nos distinguere debemus (where the law does not distinguish, we must not distinguish) and Expressio unius est exclusio alterius.\"",
        "analysis": [
            ("1. Universal Scope of Social Welfare:", "The Social Security Act is a remedial social welfare legislation enacted pursuant to police power. Lay workers in churches face the same hazards of disability, sickness, and old age as industrial workers."),
            ("2. Inapplicability of Ejusdem Generis and Noscitur a Sociis:", "The statutory definition of 'employer' in the SSS Act is comprehensive and clear. Construction canons cannot be used to restrict clear universal words."),
            ("3. Explicit Statutory Exemptions:", "Congress explicitly enumerated exempt services in Section 8(j). By including agricultural and domestic exemptions but omitting religious institutions, the legislative intent to cover religious lay workers is conclusive under Expressio Unius.")
        ],
        "analysis_plain": "Churches employ janitors, teachers, and clerks who get sick, grow old, and retire. SSS is designed to protect all human workers. Because Congress created an explicit list of exemptions and chose not to include religious institutions, the Church cannot invent an exemption through interpretation canons.",
        "analysis_recite": "\"Sir/Ma'am, the Court held that the maxims Ejusdem Generis and Noscitur a Sociis cannot be used to defeat the plain universal language of a social welfare statute. Under Ubi Lex Non Distinguit and Expressio Unius, religious and charitable lay workers are fully covered by SSS.\"",
        "conclusion": "The Supreme Court AFFIRMED the resolution of the Social Security Commission, DECLARING religious and charitable institutions subject to compulsory SSS coverage.",
        "conclusion_plain": "The Church's petition was denied and religious institutions were declared subject to mandatory SSS.",
        "conclusion_recite": "\"The Supreme Court affirmed compulsory SSS coverage for religious institutions, holding that construction maxims cannot narrow broad social legislation.\"",
        "syllabus": "• Chapter III: Basic Guidelines in the Construction and Interpretation of Laws\n  - B. Considerations within the Statute: Inapplicability of Noscitur a Sociis & Ubi Lex Non Distinguit in Social Legislation",
        "latin_maxims": [
            ("Ubi lex non distinguit, nec nos distinguere debemus (where the law does not distinguish, we should not distinguish)", "Where the law makes no distinction, we ought not to distinguish.", "The SSS Act does not distinguish between profit and non-profit employers."),
            ("Expressio unius est exclusio alterius (the express mention of one thing is the exclusion of another)", "The express mention of one thing implies the exclusion of others.", "The express list of SSS exemptions in Section 8(j) excludes unmentioned religious institutions."),
            ("Salus populi est suprema lex (the welfare of the people is the supreme law)", "The welfare of the people is the supreme law.", "Social security protection for workers takes precedence over institutional exemptions.")
        ],
        "primary_maxim": "Ubi lex non distinguit, nec nos distinguere debemus\n(where the law does not distinguish, we should not distinguish / SSS Act covers all employment without distinguishing profit from non-profit)",
        "secondary_maxims": "• Expressio unius est exclusio alterius (express exemptions exclude religious institutions)\n• Salus populi est suprema lex (the welfare of workers is supreme)",
        "violation_text": "The petitioner attempted to use Ejusdem Generis and Noscitur a Sociis to manufacture an unwritten religious exemption to a universal social welfare law.",
        "execution_text": "Universal Construction of Social Welfare Statutes: Where a social welfare statute employs all-inclusive language and provides specific exemptions, courts will not apply construction canons to create additional exemptions.",
        "statcon_plain": "When a law protecting all working people lists specific exemptions, courts cannot invent a new exemption for religious employers.",
        "statcon_recite": "\"Sir/Ma'am, Roman Catholic Archbishop v. SSC establishes that statutory construction maxims like Ejusdem Generis cannot be used to restrict universal social legislation—Ubi lex non distinguit.\""
    }
]

print(f"Loaded {len(cases_p2_part2)} cases for Phase 2 Part 2 (Cases 32-41).")
