# phase3_cases_part2.py
# Manila Law College - Statutory Construction Case Digests
# Chapter IV-B & IV-C: Extrinsic Aids & Presumptions (Cases 60 to 69)

cases_p3_part2 = [
    {
        "num": 60,
        "title": "Metropolitan Manila Development Authority (MMDA) v. Dante O. Garin",
        "citation": "G.R. No. 130230 | April 15, 2005 | 456 SCRA 176 | En Banc | Ponente: J. Chico-Nazario",
        "plaintiff": "Metropolitan Manila Development Authority (MMDA) (Petitioner)",
        "defendant": "Dante O. Garin (Respondent)",
        "court": "Regional Trial Court of Parañaque City (Branch 258) / Supreme Court En Banc",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning whether MMDA has statutory police power under Republic Act No. 7924 to confiscate and suspend driver's licenses.",
        "facts": "Atty. Dante Garin was flagged down by an MMDA traffic enforcer in Parañaque City for illegal parking. The enforcer confiscated Garin's driver's license and issued a Traffic Violation Receipt (TVR) pursuant to MMDA Memorandum Circular No. 92-005. Garin filed an injunction suit before the RTC, arguing that MMDA possesses no police power or legislative authority under its charter (R.A. No. 7924) to confiscate driver's licenses. The MMDA argued that Section 5(f) of RA 7924, which empowers it to 'install and administer a single ticketing system and organize administrative suspensions,' implies the power to confiscate licenses.",
        "plain_facts": "An MMDA traffic enforcer confiscated a lawyer's driver's license for illegal parking. The lawyer sued, claiming MMDA has no legal power to seize licenses because it is not a police force and has no lawmaking powers. The Supreme Court examined the Congressional Deliberations (Legislative Debates) of RA 7924 as an extrinsic aid and confirmed that Congress explicitly stripped MMDA of police power and legislative authority, turning it into an administrative coordination agency only. Therefore, MMDA cannot confiscate driver's licenses without a local ordinance.",
        "issue": "Whether or not the MMDA has the statutory authority under R.A. No. 7924 to confiscate driver's licenses, using Legislative Debates and Congressional Journals as Extrinsic Aids.",
        "issue_plain": "Does the MMDA have the legal power to confiscate driver's licenses under its charter, when checked against Congressional debates?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether MMDA possesses police power to confiscate driver's licenses under RA 7924, testing Legislative Debates and Congressional Records as Extrinsic Aids to Construction and Potestas Delegata Non Delegari Potest.\"",
        "answer": "NO. The MMDA has NO STATUTORY AUTHORITY to confiscate driver's licenses. Extrinsic aids—specifically the LEGISLATIVE DEBATES on R.A. No. 7924—reveal that Congress explicitly intended to create the MMDA as an administrative coordinating body, NOT a political police power agency.",
        "answer_plain": "No. The transcripts of the Senate and House debates prove that lawmakers deliberately refused to give MMDA police power. MMDA is an administrative agency that coordinates services; it cannot take away licenses unless authorized by a valid local municipal ordinance.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court held that under Legislative Debates as an Extrinsic Aid, Congress explicitly stripped MMDA of police power and legislative authority. As affirmed in MMDA v. Bel-Air Village, MMDA cannot confiscate driver's licenses under RA 7924 without a specific delegation from local sanggunians.\"",
        "legal_basis": [
            ("1. Republic Act No. 7924 (MMDA Charter):", "Creates the MMDA as an administrative planning and coordinating agency for basic services."),
            ("2. Legislative Debates and Congressional Records as Extrinsic Aids:", "Statements and deliberations of legislators during floor debates reveal the definitive legislative intent regarding agency powers."),
            ("3. Potestas Delegata Non Delegari Potest (a delegated power cannot be delegated):", "Police power is inherently legislative; an administrative agency cannot assume police power by implication.")
        ],
        "legal_basis_plain": "RA 7924, Legislative Debates as Extrinsic Aids, and Potestas Delegata Non Delegari Potest.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is RA 7924, interpreted through Legislative Debates and Committee Records as Extrinsic Aids under the doctrine of Potestas delegata non delegari potest.\"",
        "analysis": [
            ("1. Legislative Intent from Floor Debates:", "The transcripts of the Senate deliberations (speeches of Senators Macapagal-Arroyo, Tolentino, and Biazon) clearly show that Congress explicitly rejected giving MMDA police power or ordinance-making authority."),
            ("2. Administrative vs. Police Authority:", "MMDA is limited to planning, monitoring, and coordinating functions. Regulating and seizing driver's licenses is an exercise of police power belonging exclusively to the LTO and local government units under the Local Government Code."),
            ("3. Subordination of Administrative Regulations:", "MMDA circulars ordering automatic license confiscation are ultra vires and void because they exceed the statutory authority conferred by Congress.")
        ],
        "analysis_plain": "When reading the official transcripts of the Senate debates on RA 7924, the Senators clearly agreed: 'MMDA is not a local government; it has no police power.' Because the legislative debates show Congress deliberately withheld the power to seize licenses, the MMDA cannot give itself that power through internal circulars.",
        "analysis_recite": "\"Sir/Ma'am, the Court utilized the Congressional Records as an extrinsic aid. The debates prove that Congress deliberately designed MMDA without police power. Under the principle that administrative powers cannot exceed statutory grants, MMDA's license confiscation was declared ultra vires.\"",
        "conclusion": "The Supreme Court AFFIRMED the trial court decision, ENJOINED the MMDA from confiscating driver's licenses without statutory or ordinance authority, and ORDERED the return of Garin's license.",
        "conclusion_plain": "The lawyer won and MMDA was prohibited from confiscating driver's licenses without an ordinance.",
        "conclusion_recite": "\"The Supreme Court prohibited MMDA from confiscating driver's licenses, using Congressional debates as an extrinsic aid to define the limits of agency power.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - B. Extrinsic Aids: Legislative Debates and Congressional Records (Limits of Administrative Agency Powers)",
        "latin_maxims": [
            ("Potestas delegata non delegari potest (a delegated power cannot be delegated)", "Delegated power cannot be further delegated.", "Police power is vested in the Legislature and local sanggunians; MMDA cannot assume it by implication."),
            ("Optima statuti interpretatrix est ipsum statutum (the best interpreter of a statute is the statute itself)", "The best interpreter of a statute is the statute itself.", "Congressional records and debates explain the true boundaries of the statutory enactment."),
            ("Ultra vires non potest (an act beyond powers is void)", "Beyond powers cannot stand.", "Administrative circulars issued without statutory authorization are null and void.")
        ],
        "primary_maxim": "Potestas delegata non delegari potest\n(a delegated power cannot be delegated / MMDA cannot exercise police power to confiscate licenses without statutory or ordinance authority)",
        "secondary_maxims": "• Optima statuti interpretatrix (legislative debates as extrinsic guide)\n• Ultra vires non potest (nullity of unauthorized administrative acts)",
        "violation_text": "MMDA attempted to arrogate inherent police powers through administrative circulars in direct defiance of the legislative intent recorded in Congressional debates.",
        "execution_text": "Legislative Debates as Extrinsic Aids: The record of floor debates in Congress is a recognized extrinsic aid to determine the precise nature, scope, and limitations of powers granted to administrative agencies.",
        "statcon_plain": "If you want to know what a law means, read what the Senators and Congressmen said when they debated and voted on the bill.",
        "statcon_recite": "\"Sir/Ma'am, MMDA v. Garin is the leading authority on using Congressional Floor Debates as an extrinsic aid to establish that MMDA lacks police power to seize licenses.\""
    },
    {
        "num": 61,
        "title": "Commissioner of Internal Revenue v. SM Prime Holdings, Inc. and First Asia Realty Development Corp.",
        "citation": "G.R. No. 183505 | February 26, 2010 | 613 SCRA 774 | First Division | Ponente: J. Del Castillo",
        "plaintiff": "Commissioner of Internal Revenue (Petitioner)",
        "defendant": "SM Prime Holdings, Inc. and First Asia Realty Development Corp. (Respondents)",
        "court": "Court of Tax Appeals (En Banc) / Supreme Court",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning whether cinema ticket sales are subject to Value-Added Tax (VAT) under Section 108 of the National Internal Revenue Code of 1997 and Revenue Memorandum Circular (RMC) No. 28-2001.",
        "facts": "The BIR issued Revenue Memorandum Circular (RMC) No. 28-2001 declaring that gross receipts from cinema ticket sales and film exhibition are subject to 10% Value-Added Tax (VAT) under Section 108 of the NIRC of 1997 as 'services of the same kind'. Based on this circular, the CIR assessed SM Prime Holdings and First Asia Realty for deficiency VAT on their movie theater admissions. SM Prime protested, arguing that: (1) Section 108 does not include cinema exhibition in its enumeration of taxable services; (2) under the Local Government Code (Section 140), cinema admissions are subject to local amusement tax, and legislative history shows Congress never intended to impose national VAT on movie tickets; and (3) the BIR cannot expand the Tax Code via an administrative circular.",
        "plain_facts": "The BIR issued a memorandum circular saying all movie ticket sales in mall cinemas must pay a 10% national VAT. SM Prime challenged the tax, pointing out that movie theaters already pay local amusement taxes to cities, and that the Tax Code never mentioned cinema tickets under VAT. The Supreme Court investigated the Legislative History of the Tax Code as an extrinsic aid and confirmed that Congress deliberately exempted cinema admissions from national VAT to avoid double taxation with local amusement taxes. The BIR circular was declared illegal.",
        "issue": "Whether or not gross receipts from cinema theater admissions are subject to Value-Added Tax (VAT) under Section 108 of the NIRC, using Legislative History and Contemporaneous Construction as Extrinsic Aids.",
        "issue_plain": "Are cinema ticket sales subject to national VAT, when examined through the legislative history of the Tax Code?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether cinema admissions are subject to VAT under Section 108 NIRC, testing Legislative History as an Extrinsic Aid to Construction and the rule that Administrative Regulations cannot expand the Tax Code (Strictissimi Juris).\"",
        "answer": "NO. Cinema ticket admissions are NOT subject to Value-Added Tax (VAT). EXTRINSIC AIDS—specifically the LEGISLATIVE HISTORY of the NIRC and VAT enactments—demonstrate that Congress deliberately excluded cinema operators from VAT coverage to leave the taxation of cinemas exclusively to local government amusement taxes.",
        "answer_plain": "No. The legislative history shows Congress deliberately left out cinema tickets from VAT because local cities already tax movie tickets with an amusement tax. The BIR cannot invent a new VAT on movies through an administrative circular.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court held that under Legislative History as an Extrinsic Aid, Congress consistently excluded motion picture exhibition from the VAT system. Under Strictissimi Juris, the BIR cannot expand Section 108 through RMC No. 28-2001, rendering the circular null and void.\"",
        "legal_basis": [
            ("1. Section 108, National Internal Revenue Code of 1997:", "Enumerates transactions and services subject to VAT, omitting cinema and theatrical admissions."),
            ("2. Legislative History and Prior Enactments as Extrinsic Aids:", "The evolution of VAT statutes from E.O. 273 to R.A. 7716 and R.A. 8424 shows the continuous legislative intent to exclude cinema admissions."),
            ("3. Strictissimi Juris (of the strictest interpretation) in Tax Imposition:", "Taxes cannot be imposed by administrative implication; statutes are strictly construed against the taxing authority.")
        ],
        "legal_basis_plain": "Section 108 NIRC, Legislative History as Extrinsic Aid, and Strictissimi Juris.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 108 NIRC, interpreted through Legislative History as an Extrinsic Aid and the bedrock canon Strictissimi Juris in taxation.\"",
        "analysis": [
            ("1. Legislative Evolution of VAT Laws:", "From the original VAT law (E.O. No. 273) through the Expanded VAT (R.A. No. 7716) and the 1997 Tax Code, cinema exhibition was never included in the VAT base. In fact, proposed amendments to include movie theaters were repeatedly rejected by Congress."),
            ("2. Harmonization with Local Government Code:", "Under Section 140 LGC, local governments are granted the exclusive power to levy amusement taxes on cinemas. Congress avoided double taxation by keeping cinema admissions outside the national VAT system."),
            ("3. Administrative Regulations Cannot Legislate:", "RMC No. 28-2001 was an unauthorized exercise of administrative legislation that attempted to tax a service that the Legislature deliberately excluded.")
        ],
        "analysis_plain": "The Court traced the entire history of tax laws passed by Congress over 20 years. Every time someone proposed adding movie tickets to the VAT law, Congress voted NO. When the law is traced historically, the legislative intent is crystal clear: only cities collect amusement tax on movies, and the BIR cannot change the law with a circular.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied Legislative History as an extrinsic aid. The legislative trail shows continuous, deliberate congressional refusal to include cinema exhibitions in VAT. The Court struck down the BIR circular for usurping the legislative power of Congress.\"",
        "conclusion": "The Supreme Court DENIED the CIR's petition, AFFIRMED the Court of Tax Appeals, and DECLARED RMC No. 28-2001 NULL AND VOID for imposing an unauthorized tax on cinema admissions.",
        "conclusion_plain": "SM Prime won; the cinema VAT assessment and BIR circular were declared illegal and void.",
        "conclusion_recite": "\"The Supreme Court voided the BIR circular and cancelled the VAT assessment on cinema tickets under the doctrine of Legislative History.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - B. Extrinsic Aids: Legislative History of the Statute & Limits of Administrative Rule-Making (Strictissimi Juris)",
        "latin_maxims": [
            ("Strictissimi juris (of the strictest interpretation)", "Of the strictest law.", "Tax statutes are construed strictly against the government; taxes cannot be created by administrative regulation."),
            ("Optima statuti interpretatrix est ipsum statutum (the best interpreter of a statute is the statute itself)", "The best interpreter of a statute is the statute itself.", "Legislative history and amendments reveal the true statutory boundaries of the VAT law."),
            ("Potestas delegata non delegari potest (a delegated power cannot be delegated)", "Delegated power cannot be further delegated.", "The BIR cannot usurp the constitutional power of Congress to impose new taxes.")
        ],
        "primary_maxim": "Strictissimi juris\n(of the strictest interpretation / tax laws are strictly construed against the government; administrative circulars cannot expand the VAT base)",
        "secondary_maxims": "• Optima statuti interpretatrix (legislative history as guide)\n• Potestas delegata non delegari potest (administrative agencies cannot legislate)",
        "violation_text": "The BIR issued an administrative circular that created a new tax on cinema tickets in direct violation of the legislative history of the Tax Code.",
        "execution_text": "Legislative History as a Constraint on Executive Agencies: The legislative history and evolution of a statute serve as an authoritative extrinsic aid to prevent administrative agencies from expanding tax liabilities beyond statutory boundaries.",
        "statcon_plain": "Tracing the history of how a law was changed over the years proves what Congress wanted, preventing tax agencies from inventing new taxes.",
        "statcon_recite": "\"Sir/Ma'am, CIR v. SM Prime Holdings is the leading case on Legislative History as an extrinsic aid to invalidate unauthorized administrative tax regulations.\""
    },
    {
        "num": 62,
        "title": "Laxamana v. Baltazar",
        "citation": "G.R. No. L-5955 | September 19, 1952 | 92 Phil. 32 | En Banc | Ponente: J. Bengzon",
        "plaintiff": "Jose Laxamana (Petitioner)",
        "defendant": "Flaviano Baltazar (Respondent)",
        "court": "Supreme Court En Banc (Original Action for Quo Warranto)",
        "nature": "Petition for Quo Warranto concerning whether the Vice-Mayor or a Provincial Governor's appointee succeeds as Mayor during the temporary suspension of the Municipal Mayor under Section 2195 of the Revised Administrative Code.",
        "facts": "The Municipal Mayor of Sexmoan, Pampanga was suspended from office pending administrative charges. The Provincial Governor appointed Flaviano Baltazar to take over as Mayor. The elected Vice-Mayor, Jose Laxamana, contested the appointment and claimed the right to assume the office of Mayor pursuant to Section 2195 of the Revised Administrative Code, which provided that 'upon the occasion of the absence, suspension, or other temporary disability of the mayor, his duties shall be discharged by the vice-mayor.' Baltazar argued that Section 21(a) of the Revised Election Code gave the Governor the general power to fill vacancies in municipal offices.",
        "plain_facts": "The mayor of a town was suspended. The Provincial Governor appointed an outsider to act as mayor. The elected Vice-Mayor filed a lawsuit, arguing that the Administrative Code explicitly says that when the mayor is suspended, the vice-mayor takes over the duties. The outsider argued that the Election Code gave the Governor the right to fill vacancies. The Supreme Court investigated the legislative history of local government succession and ruled that Section 2195 specifically provides for automatic temporary succession by the vice-mayor, which prevails over the general vacancy power of the Governor.",
        "issue": "Whether or not the Vice-Mayor automatically assumes the office of Mayor during the temporary suspension of the incumbent Mayor, using Legislative History as an Extrinsic Aid.",
        "issue_plain": "Does the Vice-Mayor automatically take over when the Mayor is suspended, or can the Governor appoint someone else?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the Vice-Mayor succeeds to the office during temporary suspension of the Mayor under Section 2195 of the Administrative Code, testing Legislative History and Generalia Specialibus Non Derogant.\"",
        "answer": "YES. The VICE-MAYOR automatically assumes the duties of the Mayor during the Mayor's temporary suspension. Section 2195 of the Revised Administrative Code is a SPECIAL PROVISION on temporary disability that prevails over the general vacancy rules of the Election Code.",
        "answer_plain": "Yes. The law specifically says the Vice-Mayor takes over when the Mayor is suspended. The Governor's general power to fill permanent vacancies cannot be used to bypass the elected Vice-Mayor during temporary suspensions.",
        "answer_recite": "\"Yes, Sir/Ma'am. The Supreme Court held that under Legislative History as an Extrinsic Aid and Generalia specialibus non derogant, Section 2195 of the Revised Administrative Code specifically mandates automatic temporary succession by the Vice-Mayor. The Governor has no power to appoint a substitute where the law provides an automatic successor.\"",
        "legal_basis": [
            ("1. Section 2195, Revised Administrative Code:", "Specific provision mandating that upon the absence, suspension, or temporary disability of the mayor, his duties shall be discharged by the vice-mayor."),
            ("2. Section 21(a), Revised Election Code:", "General provision governing the filling of vacancies in municipal offices."),
            ("3. Generalia Specialibus Non Derogant (general provisions yield to special provisions):", "The specific automatic succession rule for temporary disability controls over general vacancy filling."),
            ("4. Legislative History as an Extrinsic Aid:", "The historical evolution of municipal administration laws confirms the statutory policy of succession through the vice-mayor.")
        ],
        "legal_basis_plain": "Section 2195 RAC, Section 21(a) Election Code, Generalia Specialibus Non Derogant, and Legislative History.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Section 2195 of the Revised Administrative Code, applied under Generalia specialibus non derogant (general laws yield to special provisions) and Legislative History as an Extrinsic Aid.\"",
        "analysis": [
            ("1. Legislative Evolution of Municipal Succession:", "The historical purpose of creating the office of Vice-Mayor was precisely to have a readily available, democratically elected substitute to assume executive duties instantly during the mayor's temporary absence or disability."),
            ("2. Distinction Between Permanent Vacancy and Temporary Disability:", "Section 21(a) of the Election Code governs permanent vacancies (death, permanent resignation, removal). Section 2195 of the Administrative Code specifically governs temporary suspensions."),
            ("3. Democratic Will of the Electorate:", "The electorate elected the Vice-Mayor with the expectation that he would step into the Mayor's shoes when needed; executive appointment of a political favorite violates the statutory scheme.")
        ],
        "analysis_plain": "Why do people elect a Vice-Mayor? To take over when the Mayor is sick, away, or suspended! If the Governor could appoint a political ally whenever the Mayor is suspended, the office of Vice-Mayor would be meaningless. The specific succession law controls.",
        "analysis_recite": "\"Sir/Ma'am, the Court examined the legislative history of municipal governance. The specific text of Section 2195 RAC guarantees automatic succession by the Vice-Mayor during temporary suspensions. Under Generalia Specialibus Non Derogant, this specific rule defeats general gubernatorial vacancy powers.\"",
        "conclusion": "The Supreme Court GRANTED the petition for Quo Warranto, OUSTED respondent Baltazar, and DECLARED petitioner Vice-Mayor Jose Laxamana entitled to discharge the duties of Mayor.",
        "conclusion_plain": "The Vice-Mayor won and was declared the rightful acting Mayor.",
        "conclusion_recite": "\"The Supreme Court ousted the Governor's appointee and declared the Vice-Mayor the lawful acting Mayor under Section 2195 RAC.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - B. Extrinsic Aids: Legislative History & Generalia Specialibus Non Derogant (Local Executive Succession)",
        "latin_maxims": [
            ("Generalia specialibus non derogant (general things do not derogate from special things)", "General words do not derogate from special provisions.", "The specific temporary succession rule in Section 2195 RAC prevails over general vacancy provisions in the Election Code."),
            ("Ratio legis est anima legis (the reason of the law is the soul of the law)", "The reason of the law is the soul of the law.", "The legislative reason for creating the vice-mayoralty is to ensure continuous democratic local executive succession."),
            ("Salus populi est suprema lex (the welfare of the people is the supreme law)", "The welfare of the people is the supreme law.", "Respecting the democratic choice of the voters for Vice-Mayor preserves local government stability.")
        ],
        "primary_maxim": "Generalia specialibus non derogant\n(general things do not derogate from special provisions / specific temporary succession rule for Vice-Mayor under Section 2195 RAC overrides general vacancy powers)",
        "secondary_maxims": "• Ratio legis est anima legis (purpose of the vice-mayoralty)\n• Salus populi est suprema lex (democratic electoral succession)",
        "violation_text": "The Provincial Governor attempted to use a general vacancy statute to override the specific statutory succession mechanism enacted for the Vice-Mayor.",
        "execution_text": "Primacy of Specific Succession Provisions: Where a statute creates an automatic line of succession for temporary disability, executive appointing authorities cannot create artificial vacancies to install political appointees.",
        "statcon_plain": "A specific law saying 'the vice-mayor takes over when the mayor is suspended' beats a general law about appointing replacements.",
        "statcon_recite": "\"Sir/Ma'am, Laxamana v. Baltazar is the foundational jurisprudence harmonizing local government succession through Legislative History and Generalia specialibus non derogant.\""
    },
    {
        "num": 63,
        "title": "Rustan Ang v. Court of Appeals and Irish Sagud",
        "citation": "G.R. No. 182835 | April 20, 2010 | 618 SCRA 592 | Third Division | Ponente: J. Abad",
        "plaintiff": "Rustan Ang (Petitioner)",
        "defendant": "Court of Appeals and Irish Sagud (Respondents)",
        "court": "Regional Trial Court of Baguio City (Branch 6) / Court of Appeals",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning whether obscene picture messages (MMS) sent via cellular phone constitute 'electronic documents' under the Rules on Electronic Evidence and Republic Act No. 8792 (E-Commerce Act).",
        "facts": "Rustan Ang sent naked and obscene pictures of his former girlfriend Irish Sagud through cellular phone Multimedia Messaging Service (MMS) with extortion demands. He was criminally charged with violation of the Anti-Photo and Video Voyeurism Act and the RPC. During trial, the prosecution presented digital camera photographs of the cell phone screen showing the text and picture messages. Ang objected to the admissibility of the photos, arguing that under the 2001 Rules on Electronic Evidence (A.M. No. 01-7-01-SC) and the E-Commerce Act (R.A. No. 8792), an 'electronic document' refers only to computer data files, not to cellular phone SMS/MMS messages.",
        "plain_facts": "A man sent naked pictures of his ex-girlfriend via cell phone MMS to blackmailed her. In court, prosecutors presented photos of the cell phone screen showing the messages. The man argued that the digital messages were inadmissible because the Electronic Evidence Rules only apply to computers, not cell phones! The Supreme Court rejected his argument, using Extrinsic Aids and contemporaneous technological realities to rule that cell phone messages are electronic documents.",
        "issue": "Whether or not cell phone text messages (SMS) and multimedia messages (MMS) qualify as 'electronic documents' under the Rules on Electronic Evidence, using Extrinsic Aids and Contemporaneous Construction.",
        "issue_plain": "Are cell phone text and picture messages considered 'electronic documents' that can be used as evidence in court?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether SMS and MMS cellular communications qualify as electronic documents under the Rules on Electronic Evidence, testing Contemporaneous Construction and Extrinsic Aids in interpreting modern technological terms.\"",
        "answer": "YES. Cell phone text and multimedia messages ARE ELECTRONIC DOCUMENTS within the contemplation of the Rules on Electronic Evidence. Remedial and evidentiary rules must be construed in light of CONTEMPORANEOUS TECHNOLOGICAL DEVELOPMENTS to maintain efficacy.",
        "answer_plain": "Yes. Cell phones are pocket computers. A digital text message or picture message stored on a phone is an electronic document. Evidentiary rules must be interpreted to cover modern technology so criminals cannot hide behind technicalities.",
        "answer_recite": "\"Yes, Sir/Ma'am. The Supreme Court held that under Contemporaneous Construction and purposive interpretation of the Rules on Electronic Evidence (A.M. No. 01-7-01-SC) in relation to RA 8792, cellular phone text messages (SMS) and multimedia messages (MMS) constitute electronic documents and are admissible in evidence.\"",
        "legal_basis": [
            ("1. Rule 2, Section 1(h), Rules on Electronic Evidence (A.M. No. 01-7-01-SC):", "Defines electronic documents to include information generated, received, or stored by electronic, optical, or similar means."),
            ("2. Republic Act No. 8792 (Electronic Commerce Act of 2000):", "Statutory recognition of electronic data messages and digital signatures."),
            ("3. Contemporanea Expositio Est Optima Et Fortissima In Lege (contemporaneous exposition is the best and strongest in the law):", "Evidentiary rules are interpreted in light of existing technological realities to achieve justice.")
        ],
        "legal_basis_plain": "Rules on Electronic Evidence, RA 8792, and Contemporaneous Construction in modern technology.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Rule 2 of the Rules on Electronic Evidence and RA 8792, interpreted under Contemporanea expositio est optima et fortissima in lege (contemporaneous exposition is the best in law).\"",
        "analysis": [
            ("1. Technological Breadth of 'Electronic Document':", "An electronic document is not confined to desktop computer files. Modern cell phones process and store digital data electronically. An SMS or MMS is an electronic data message generated and stored by electronic means."),
            ("2. Purposive Construction of Remedial Rules:", "The Supreme Court promulgated the Rules on Electronic Evidence precisely to modernize the administration of justice and accommodate digital communications."),
            ("3. Admissibility of Ephemeral Communications:", "Digital photos of cell phone screens displaying MMS messages are admissible as secondary or direct evidence of the communication when properly authenticated.")
        ],
        "analysis_plain": "A smartphone is just a small computer. When you send an MMS photo, it is generated and stored using digital computer code. If courts said phone messages aren't 'electronic', cyber-criminals and blackmailers would walk free. The Court adapted the definition to match modern technological reality.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied progressive contemporaneous construction. Evidentiary rules must keep pace with technological evolution. The Court held that cell phone SMS and MMS messages fall squarely within the definition of electronic data messages under RA 8792 and the Electronic Evidence Rules.\"",
        "conclusion": "The Supreme Court DENIED Ang's petition, AFFIRMED the admissibility of the MMS messages, and UPHELD his criminal conviction.",
        "conclusion_plain": "The conviction was affirmed and the cell phone MMS evidence was ruled completely admissible.",
        "conclusion_recite": "\"The Supreme Court affirmed the conviction, holding that cellular SMS/MMS messages are electronic documents admissible under the Rules on Electronic Evidence.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - B. Extrinsic Aids: Contemporaneous Technological Context & Progressive Construction of Remedial Rules",
        "latin_maxims": [
            ("Contemporanea expositio est optima et fortissima in lege (contemporaneous exposition is the best and strongest in the law)", "Contemporaneous exposition is the best and strongest in law.", "Remedial rules must be construed in harmony with contemporary technological realities."),
            ("Ut res magis valeat quam pereat (that the thing may rather have effect than perish)", "That the thing may have effect rather than perish.", "The Rules on Electronic Evidence must be construed to make electronic proof effective in criminal prosecutions."),
            ("Lex non intendit aliquid impossibile aut absurdum (the law does not intend anything impossible or absurd)", "The law does not intend an absurdity.", "It is absurd to exclude mobile phone digital data from the scope of electronic evidence.")
        ],
        "primary_maxim": "Contemporanea expositio est optima et fortissima in lege\n(contemporaneous exposition is the best in law / evidentiary rules must be construed to embrace contemporary mobile and digital technologies)",
        "secondary_maxims": "• Ut res magis valeat quam pereat (construction to preserve evidentiary efficacy)\n• Lex non intendit absurdum (avoiding absurd evidentiary exclusions)",
        "violation_text": "The petitioner attempted to construct a pedantic distinction between computers and mobile phones to exclude incriminating digital evidence.",
        "execution_text": "Progressive Construction of Evidentiary Codes: Procedural and evidentiary rules must be given an expansive, progressive construction to encompass evolving technologies and digital communications.",
        "statcon_plain": "Rules on electronic evidence must be interpreted to include smartphones and modern apps, not just ancient desktop computers.",
        "statcon_recite": "\"Sir/Ma'am, Ang v. Court of Appeals is the leading case on the progressive contemporaneous construction of electronic evidence rules, confirming that SMS/MMS messages are electronic documents.\""
    },
    {
        "num": 64,
        "title": "Alvarez v. Guingona",
        "citation": "G.R. No. 118303 | January 31, 1996 | 252 SCRA 695 | En Banc | Ponente: J. Hermosisima, Jr.",
        "plaintiff": "Alvarez (Petitioner)",
        "defendant": "Executive Secretary Teofisto Guingona, Jr. (Respondent)",
        "court": "Supreme Court En Banc (Original Action for Prohibition)",
        "nature": "Petition for Prohibition challenging the constitutionality of Republic Act No. 7720 converting the Municipality of Santiago, Isabela into an independent component city under the Enrolled Bill Doctrine.",
        "facts": "Petitioners challenged the validity of Republic Act No. 7720 (Charter of the City of Santiago), contending that the law did not originate exclusively in the House of Representatives as required by Article VI, Section 24 of the 1987 Constitution for local bills. Petitioners cited entries in the Congressional Journals showing that the Senate passed its own version before receiving the House bill. The respondents invoked the ENROLLED BILL DOCTRINE, showing that the final bill was duly signed by the Speaker of the House and the Senate President and approved by the President of the Philippines.",
        "plain_facts": "A group of citizens challenged the law that turned the town of Santiago, Isabela into a city, claiming the law was unconstitutional because the Senate started working on the bill before the House finished it, citing entries in the legislative journals. The government defended the law using the Enrolled Bill Doctrine, showing that the final official copy of the bill was formally signed by the Senate President, Speaker of the House, and President of the Philippines. The Supreme Court upheld the city charter, ruling that the Enrolled Bill is conclusive evidence of the regular passage of a statute.",
        "issue": "Whether or not the Enrolled Bill Doctrine prevails over Congressional Journals and records in establishing the regular constitutional enactment of a statute (R.A. No. 7720).",
        "issue_plain": "Does the officially signed copy of a law (Enrolled Bill) beat journal notes when someone challenges how the law was passed in Congress?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether RA 7720 is constitutional under the Enrolled Bill Doctrine, testing whether an Enrolled Bill is conclusive proof of regular enactment over conflicting entries in Congressional Journals.\"",
        "answer": "YES. The ENROLLED BILL DOCTRINE prevails. The signing of a bill by the Speaker of the House and the Senate President and its certification as having passed both Houses is CONCLUSIVE PROOF of its due enactment, which courts cannot question by inspecting legislative journals.",
        "answer_plain": "Yes. When the heads of both Houses of Congress sign a law and send it to the President, that official paper (Enrolled Bill) is final and conclusive. Courts respect the separation of powers and will not go digging through legislative diary notes to second-guess Congress.",
        "answer_recite": "\"Yes, Sir/Ma'am. The Supreme Court held that under the Enrolled Bill Doctrine and the principle of separation of powers, an enrolled bill signed by the Senate President and House Speaker carries absolute verity and is conclusive upon the courts as to the regular passage of the statute.\"",
        "legal_basis": [
            ("1. Article VI, Section 24 and 26, 1987 Constitution:", "Constitutional requirements for legislative enactment of local bills and enrolled bill certification."),
            ("2. The Enrolled Bill Doctrine:", "An enrolled bill signed by the leaders of Congress imports absolute verity and is conclusive of its due enactment."),
            ("3. Presumption of Regularity and Constitutionality:", "Official acts of the legislative and executive branches are presumed regular and valid under Omnia Praesumuntur Rite Esse Acta.")
        ],
        "legal_basis_plain": "Article VI 1987 Constitution, Enrolled Bill Doctrine, and Omnia Praesumuntur Rite Esse Acta.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Article VI of the Constitution, governed by the Enrolled Bill Doctrine and the presumption Omnia praesumuntur rite et solemniter esse acta (all acts are presumed to have been done regularly).\"",
        "analysis": [
            ("1. Conclusiveness of the Enrolled Bill:", "The enrolled copy of a bill, bearing the authentic signatures of the Speaker of the House and the President of the Senate, is the definitive, solemn declaration of the Legislature that the bill was regularly passed in compliance with constitutional procedures."),
            ("2. Judicial Non-Interference in Legislative Process:", "To permit courts to examine legislative journals and second-guess the accuracy of legislative certifications would violate the separation of powers and create constitutional instability."),
            ("3. Originating in the House:", "Article VI, Section 24 only requires that the legislative initiative for local bills begin in the House; the Senate has full constitutional power to propose or concur with amendments, including passing its own consolidated version.")
        ],
        "analysis_plain": "The Constitution requires checks and balances. When the Senate President and House Speaker sign an official document saying 'this bill was properly voted on and passed', the Supreme Court must respect that official word. Judges do not go through minute-by-minute journal notes to impeach the official signature of Congress.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied the Enrolled Bill Doctrine. The authentic signatures of the legislative leaders import absolute verity. Under the separation of powers and Omnia Praesumuntur Rite Esse Acta, the enrolled bill is conclusive proof of constitutional enactment.\"",
        "conclusion": "The Supreme Court DISMISSED the petition and UPHELD the constitutionality and validity of Republic Act No. 7720 creating the City of Santiago.",
        "conclusion_plain": "The petition was dismissed and the city charter was declared completely valid.",
        "conclusion_recite": "\"The Supreme Court upheld the constitutionality of RA 7720, reaffirming the conclusive authority of the Enrolled Bill Doctrine.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - B. Extrinsic Aids: The Enrolled Bill Doctrine vs. Legislative Journals (Presumption of Constitutionality)",
        "latin_maxims": [
            ("Omnia praesumuntur rite et solemniter esse acta donec probetur in contrarium (all acts are presumed to have been done regularly and with solemnity until the contrary is proved)", "All things are presumed to have been done regularly.", "The enrolled bill is conclusively presumed to have been enacted in accordance with all constitutional rules."),
            ("Res judicata pro veritate accipitur (a matter adjudged is taken for truth)", "An official matter settled is accepted as truth.", "The solemn certification of legislative leaders carries conclusive verity."),
            ("Potestas delegata non delegari potest (a delegated power cannot be delegated)", "Delegated power cannot be further delegated.", "The legislative power to certify bills belongs exclusively to the leaders of Congress.")
        ],
        "primary_maxim": "Omnia praesumuntur rite et solemniter esse acta\n(all acts are presumed to have been done regularly / the Enrolled Bill Doctrine is conclusive proof of regular legislative enactment)",
        "secondary_maxims": "• Res judicata pro veritate accipitur (conclusive verity of official acts)\n• Separation of powers doctrine",
        "violation_text": "The petitioners attempted to undermine the solemn certification of Congress by using selective journal entries to attack an enrolled bill.",
        "execution_text": "The Enrolled Bill Doctrine: An enrolled bill signed by the presiding officers of both Houses of Congress and approved by the President imports absolute verity and is conclusive upon the judiciary regarding constitutional compliance.",
        "statcon_plain": "The officially signed copy of a law by the leaders of Congress is the final, untouchable truth that the law was passed properly.",
        "statcon_recite": "\"Sir/Ma'am, Alvarez v. Guingona is the prime authority on the Enrolled Bill Doctrine: the enrolled copy of a statute prevails conclusively over legislative journals.\""
    },
    {
        "num": 65,
        "title": "Boie-Takeda Chemicals, Inc. and Philippine Investment-Management Consultants (PHINMA) v. Hon. Dionisio De La Serna",
        "citation": "G.R. No. 92174 | December 10, 1993 | 228 SCRA 329 | En Banc | Ponente: J. Feliciano",
        "plaintiff": "Boie-Takeda Chemicals, Inc. and PHINMA (Petitioners)",
        "defendant": "Hon. Dionisio De La Serna, Undersecretary of Labor and Employment (Respondent)",
        "court": "Department of Labor and Employment (DOLE) / Supreme Court En Banc",
        "nature": "Petition for Certiorari under Rule 65 challenging DOLE administrative order requiring the inclusion of sales commissions in the computation of 13th Month Pay under Presidential Decree No. 851.",
        "facts": "The Undersecretary of Labor issued an order directing Boie-Takeda and PHINMA to pay 13th month pay differentials to their medical representatives and sales employees by including SALES COMMISSIONS in the computation of 'basic salary' under P.D. No. 851 (The 13th Month Pay Law). The employers protested, arguing that Section 2 of PD 851 and its original Supplementary Rules explicitly defined 'basic salary' to EXCLUDE commissions, allowances, and profit-sharing bonuses. The DOLE Undersecretary claimed that contemporaneous executive construction and social justice required commissions that form part of regular compensation to be included.",
        "plain_facts": "The Department of Labor ordered pharmaceutical companies to include sales commissions when calculating the mandatory 13th Month Pay of sales agents. The companies objected, pointing out that the 13th Month Pay Law (PD 851) explicitly defines 'basic salary' as regular pay EXCLUDING commissions, allowances, and bonuses. The Supreme Court ruled in favor of the employers, holding that while executive agencies give contemporaneous construction, an administrative official cannot rewrite a statute or add items that the law explicitly excluded.",
        "issue": "Whether or not sales commissions are included in the computation of 'basic salary' for the purpose of the 13th Month Pay under P.D. No. 851, testing the limits of Contemporaneous Administrative Construction.",
        "issue_plain": "Can the Department of Labor order companies to include sales commissions in 13th month pay when the statute explicitly excludes commissions from 'basic salary'?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether sales commissions form part of 'basic salary' under PD 851, testing the limits of Contemporaneous Administrative Construction versus Verba Legis (the words of the law) and Expressio Unius.\"",
        "answer": "NO. Sales commissions are EXCLUDED from the computation of 'basic salary' under P.D. No. 851. Contemporaneous administrative construction CANNOT supersede, expand, or alter the clear, explicit statutory definition enacted by the lawgiver.",
        "answer_plain": "No. The law says 'basic salary' means base pay and explicitly excludes commissions and bonuses. An administrative agency cannot change the law by issuing an order that contradicts the statute.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court held that under Verba Legis and Expressio unius est exclusio alterius, PD 851 and its original rules explicitly excluded commissions from 'basic salary'. Contemporaneous administrative construction is an extrinsic aid of secondary rank; it cannot be used to rewrite the statute or impose obligations not authorized by the decree.\"",
        "legal_basis": [
            ("1. Presidential Decree No. 851 (The 13th Month Pay Law):", "Mandates payment of 13th month pay based on 'basic salary'."),
            ("2. Original Implementing Rules of PD 851 (December 22, 1975):", "Explicitly defines basic salary as excluding commissions, allowances, and bonuses."),
            ("3. Limits of Contemporaneous Construction:", "Administrative interpretation is entitled to great respect, but must yield when it is contrary to the clear text and purpose of the statute."),
            ("4. Verba Legis Non Est Recedendum (from the words of the statute there should be no departure):", "The statutory phrase 'basic salary' cannot be judicially or administratively inflated.")
        ],
        "legal_basis_plain": "PD 851, Original Implementing Rules, Limits of Contemporaneous Construction, and Verba Legis.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is PD 851, governed by Verba legis non est recedendum (from statutory words no departure) and the principle that Contemporaneous Administrative Construction cannot expand substantive law.\"",
        "analysis": [
            ("1. Plain Statutory Meaning of 'Basic Salary':", "The word 'basic' means fundamental, foundational, and standard. It refers to the fixed regular compensation, in contrast to variable, fluctuating productivity incentives like sales commissions."),
            ("2. Subordination of Executive Construction:", "The DOLE cannot expand the burden on employers by reinterpreting 'basic salary' through administrative circulars. Administrative interpretation cannot prevail over the clear statutory text."),
            ("3. Protection of Business Predictability:", "Forcing employers to pay 13th month bonuses on top of variable sales commissions contradicts the legislative compromise embodied in PD 851.")
        ],
        "analysis_plain": "'Basic' salary means the base rate you get every month regardless of sales. A commission is an extra bonus based on how many boxes of medicine you sold. The decree explicitly excluded commissions from basic salary. The Secretary of Labor cannot write a memo to add commissions back into the law.",
        "analysis_recite": "\"Sir/Ma'am, the Court defined the limits of administrative contemporaneous construction. Administrative agencies must execute the law, not amend it. Since PD 851 explicitly restricted 13th month pay to 'basic salary' excluding commissions, the DOLE order was ultra vires.\"",
        "conclusion": "The Supreme Court GRANTED the petition, ANNULLED the DOLE order, and DECLARED that sales commissions are excluded from 13th month pay computation under PD 851.",
        "conclusion_plain": "The employers won and the DOLE order forcing commissions into 13th month pay was nullified.",
        "conclusion_recite": "\"The Supreme Court annulled the DOLE order, holding that sales commissions cannot be included in basic salary under PD 851.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - B. Extrinsic Aids: Limits of Contemporaneous Administrative Construction (Verba Legis in Labor Standards)",
        "latin_maxims": [
            ("Verba legis non est recedendum (from the words of the statute there should be no departure)", "From the words of the statute there must be no departure.", "The statutory definition of 'basic salary' cannot be expanded by administrative fiat."),
            ("Contemporanea expositio non praevalet contra expressam legem (contemporaneous exposition does not prevail against express law)", "Contemporaneous construction does not prevail over clear statutory text.", "Executive interpretations must yield to the plain letter of the decree."),
            ("Potestas delegata non delegari potest (a delegated power cannot be delegated)", "Delegated power cannot be further delegated.", "Administrative agencies cannot usurp the legislative power to create new wage burdens.")
        ],
        "primary_maxim": "Contemporanea expositio non praevalet contra expressam legem\n(contemporaneous construction does not prevail against express law / DOLE cannot expand 'basic salary' in PD 851 through administrative circulars)",
        "secondary_maxims": "• Verba legis non est recedendum (plain meaning of 'basic salary')\n• Potestas delegata non delegari potest (limits of administrative rule-making)",
        "violation_text": "The DOLE attempted to use contemporaneous administrative construction to rewrite the statutory definition of 'basic salary' in PD 851.",
        "execution_text": "Limits of Contemporaneous Administrative Construction: While contemporaneous executive construction is entitled to deference, it cannot prevail over the express words of the statute (Contemporanea expositio non praevalet contra expressam legem).",
        "statcon_plain": "Executive agency memos cannot change the plain words of a law; if the law says 'commissions are excluded', the agency cannot order them included.",
        "statcon_recite": "\"Sir/Ma'am, Boie-Takeda v. De La Serna is the benchmark case defining the limits of Contemporaneous Construction: Contemporanea expositio non praevalet contra expressam legem.\""
    },
    {
        "num": 66,
        "title": "National Housing Authority (NHA) v. Hon. Floreliana Castro-Reyes and Spouses Arsenio & Amanda Posadas",
        "citation": "G.R. No. L-49439 | June 29, 1983 | 123 SCRA 245 | En Banc | Ponente: J. Vasquez",
        "plaintiff": "National Housing Authority (NHA) (Petitioner)",
        "defendant": "Hon. Floreliana Castro-Reyes (Judge, CFI Rizal) and Spouses Arsenio & Amanda Posadas (Respondents)",
        "court": "Court of First Instance of Rizal (Branch VI) / Supreme Court En Banc",
        "nature": "Petition for Certiorari and Mandamus under Rule 65 concerning just compensation formula in expropriation under Presidential Decree Nos. 464, 794, and 1224.",
        "facts": "The National Housing Authority (NHA) filed an expropriation complaint to acquire 25 hectares of land in Caloocan City for a socialized housing resettlement project. The trial court appointed commissioners who valued the property at P40.00 per square meter based on general market value. NHA protested, arguing that under Presidential Decree Nos. 464, 794, and 1224, the valuation in expropriation is strictly pegged to 'the market value declared by the owner, or the market value determined by the City Assessor, whichever is lower.' The trial judge refused to apply the presidential decrees, declaring the valuation formula unconstitutional and violative of judicial prerogative in just compensation.",
        "plain_facts": "The National Housing Authority (NHA) took private land to build socialized housing and insisted that under Marcos-era Presidential Decrees, the court must pay only the declared tax value (which was extremely low). The trial judge refused to follow the decree and awarded a fair market price, saying the decree formula was unconstitutional. The Supreme Court initially upheld the presidential decrees under the Presumption of Constitutionality and Dura Lex Sed Lex, ruling that presidential decrees had the force of statute until formally declared void. (Note: The Supreme Court later abandoned this formula in EPZA v. Dulay).",
        "issue": "Whether or not trial courts are bound by the mandatory valuation formulas in Presidential Decrees under the Presumption of Constitutionality, pending a formal En Banc declaration of nullity.",
        "issue_plain": "Were trial judges required to follow the expropriation valuation formulas in Presidential Decrees under the Presumption of Constitutionality?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether trial courts must enforce Presidential Decrees on just compensation under the Presumption of Constitutionality and Dura Lex Sed Lex, pending formal constitutional invalidation by the Supreme Court En Banc.\"",
        "answer": "YES. Under the PRESUMPTION OF CONSTITUTIONALITY, Presidential Decrees were presumed valid and binding on trial judges until formally declared unconstitutional by the Supreme Court En Banc. Lower court judges have no authority to disregard operative statutes.",
        "answer_plain": "Yes. Every statute and decree is presumed constitutional until the Supreme Court strikes it down En Banc. Lower court judges cannot unilaterally disregard an active presidential decree simply because they believe it is unfair.",
        "answer_recite": "\"Yes, Sir/Ma'am. The Supreme Court held that under the Presumption of Constitutionality and Dura lex, sed lex, Presidential Decrees had the force of law and were binding on trial courts. A lower court cannot disregard an operative statute on grounds of unconstitutionality without meeting the strict constitutional threshold for judicial review.\"",
        "legal_basis": [
            ("1. Presidential Decree Nos. 464, 794, and 1224:", "Expropriation valuation formula fixing just compensation at declared tax value or assessed value, whichever is lower."),
            ("2. Presumption of Constitutionality of Statutes:", "Every statute passed by the legislative authority is presumed constitutional; the burden of proving invalidity is beyond reasonable doubt."),
            ("3. Dura Lex, Sed Lex (the law is harsh, but it is the law):", "Judges cannot substitute their personal sense of fairness for the explicit command of the lawgiver.")
        ],
        "legal_basis_plain": "PD 464, PD 1224, Presumption of Constitutionality, and Dura Lex Sed Lex.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is PD 1224, governed by the Presumption of Constitutionality and Dura lex, sed lex (the law is harsh, but it is the law).\"",
        "analysis": [
            ("1. Force and Effect of Presidential Decrees:", "Under the 1973 Constitution, Presidential Decrees formed part of the law of the land, enjoying the same presumption of constitutionality as legislative acts."),
            ("2. Restraint on Lower Court Judicial Review:", "Trial judges are bound to apply the law as enacted. Disregarding an operative statute violates judicial hierarchy and the presumption of validity."),
            ("3. Historical Note / Subsequent Reversal in EPZA v. Dulay:", "While NHA v. Reyes upheld the decree formula under the presumption of validity, the Supreme Court En Banc subsequently declared this rigid formula unconstitutional in EPZA v. Dulay (1987) for usurping the judicial power to determine just compensation.")
        ],
        "analysis_plain": "Laws passed by the government are presumed valid and constitutional until the Supreme Court formally strikes them down. A single trial judge cannot ignore a written decree just because he thinks the compensation is too low. The judge must apply the law as written under Dura Lex Sed Lex.",
        "analysis_recite": "\"Sir/Ma'am, the Court applied the Presumption of Constitutionality. Lower courts are bound to enforce operative decrees under Dura Lex Sed Lex. Although this valuation doctrine was subsequently overturned in EPZA v. Dulay, NHA v. Reyes remains the leading historical example of the Presumption of Constitutionality.\"",
        "conclusion": "The Supreme Court GRANTED the petition, SET ASIDE the trial court's market valuation, and ORDERED the trial court to apply the statutory formula under P.D. No. 1224.",
        "conclusion_plain": "The trial court's order was set aside and the statutory decree formula was enforced under the presumption of constitutionality.",
        "conclusion_recite": "\"The Supreme Court enforced the decree formula, upholding the Presumption of Constitutionality of presidential decrees.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - C. Presumptions: Presumption of Constitutionality of Statutes (Historical Framework & Evolution to EPZA v. Dulay)",
        "latin_maxims": [
            ("Omnia praesumuntur rite et solemniter esse acta (all acts are presumed to have been done regularly)", "All acts are presumed regular and valid.", "Statutes and presidential decrees enjoy the presumption of constitutionality."),
            ("Dura lex, sed lex (the law is harsh, but it is the law)", "The law is harsh, but it is the law.", "Trial judges are duty-bound to apply the written statutory valuation formula."),
            ("Judicis est ius dicere, non dare (it is the duty of a judge to declare the law, not to make it)", "The judge must declare the law, not create it.", "Judges cannot invent their own compensation rules against explicit statutory commands.")
        ],
        "primary_maxim": "Omnia praesumuntur rite et solemniter esse acta\n(all acts are presumed to have been done regularly / Presumption of Constitutionality of legislative acts and decrees)",
        "secondary_maxims": "• Dura lex sed lex (harsh laws must be enforced by trial courts)\n• Judicis est ius dicere non dare (judges apply law, not make law)",
        "violation_text": "The trial judge violated the Presumption of Constitutionality and judicial hierarchy by unilaterally refusing to apply operative presidential decrees.",
        "execution_text": "Presumption of Constitutionality: All legislative enactments and executive decrees carry the presumption of constitutionality; lower courts must apply them until formally invalidated by the Supreme Court.",
        "statcon_plain": "Every law written in the statute books is presumed constitutional and must be followed by judges until the Supreme Court strikes it down.",
        "statcon_recite": "\"Sir/Ma'am, NHA v. Reyes is the classical authority on the Presumption of Constitutionality: trial courts are bound to enforce statutes under the presumption of regularity until declared unconstitutional.\""
    },
    {
        "num": 67,
        "title": "Aparri v. Court of Appeals",
        "citation": "G.R. No. L-30057 | January 31, 1984 | 127 SCRA 231 | Second Division | Ponente: J. Makasiar",
        "plaintiff": "Aparri (Petitioner)",
        "defendant": "Court of Appeals (Respondent)",
        "court": "Court of First Instance of Manila / Court of Appeals",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning the expiration of a fixed term of office versus illegal removal under Republic Act No. 1160 (National Resettlement and Rehabilitation Administration / NARRA).",
        "facts": "Aparri was appointed General Manager of NARRA by the Board of Directors with an express resolution fixing his term of office to expire on January 15, 1962. Upon the arrival of January 15, 1962, the Board approved a resolution declaring his term ended and appointing a successor. Aparri filed a petition for Mandamus and Quo Warranto, arguing that under the Civil Service Law and R.A. No. 1160, he enjoyed constitutional security of tenure and could not be removed without cause, contending that the Board's resolution fixing a term was void ab initio for violating the presumption of life tenure in public office.",
        "plain_facts": "The General Manager of a government resettlement agency was appointed by the Board of Directors with an explicit contract stating his term would expire on January 15, 1962. When that date arrived, the Board replaced him. He sued, claiming that public officials have security of tenure and cannot be removed without misconduct. The Supreme Court ruled that EXPIRATION OF A FIXED TERM is completely different from REMOVAL FROM OFFICE: when a term expires by law or contract, the officer simply reaches the end of his appointment, which does not violate security of tenure.",
        "issue": "Whether or not the expiration of a fixed term of office constitutes removal from office in violation of the constitutional and statutory presumption of security of tenure.",
        "issue_plain": "Does the end of a fixed term of office count as an illegal firing under the security of tenure law?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the expiration of a fixed term of office is equivalent to removal from office under RA 1160 and the Civil Service Law, testing the Distinction Between Term and Tenure and the Presumption of Regularity of Executive Appointments.\"",
        "answer": "NO. Expiration of a fixed term is NOT REMOVAL. Security of tenure applies only during the officer's term; once the term expires by statutory definition or valid appointment, the right to hold office automatically ceases without any removal taking place.",
        "answer_plain": "No. Term is the time limit written in your appointment; tenure is the actual time you hold the office. When your fixed term ends, your contract is over—you were not fired, your time simply expired. Security of tenure only protects you WHILE your term is running.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court established the bedrock distinction: 'Term' is the statutory period during which an officer may claim to hold office; 'Tenure' is the period he actually holds it. Under statutory construction, expiration of term does not constitute removal, and does not violate the presumption of security of tenure.\"",
        "legal_basis": [
            ("1. Republic Act No. 1160 (NARRA Charter):", "Empowers the Board of Directors to appoint and fix the terms of management personnel."),
            ("2. Constitutional and Statutory Security of Tenure:", "Protects civil service officers against removal without cause during their lawful term."),
            ("3. Distinction Between Term and Tenure:", "Term is fixed by statute or appointment; tenure depends on the incumbent's actual holding of office.")
        ],
        "legal_basis_plain": "RA 1160, Civil Service Law, Distinction between Term and Tenure, and Presumption of Regularity.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is RA 1160, construed under the doctrinal distinction between Term and Tenure and the Presumption of Regularity in public appointments.\"",
        "analysis": [
            ("1. The Concept of Term of Office:", "A term of office is the time limit fixed by law or valid executive resolution during which an officer may hold office. When the term expires, the office becomes vacant by operation of law."),
            ("2. Absence of Removal:", "Removal implies the ouster of an incumbent before the expiration of his term. When the term naturally ends, there is no removal, but a mere severance of official relations through expiration of statutory appointment."),
            ("3. Presumption of Validity of Board Action:", "The Board acted within its statutory powers under RA 1160 in fixing the term; its actions carry the presumption of regularity.")
        ],
        "analysis_plain": "If your contract says you work from January 1 to December 31, leaving on December 31 is not a termination—it's just the end of the contract. The Civil Service law stops bosses from firing you in July without cause, but it does not make a 1-year contract last forever.",
        "analysis_recite": "\"Sir/Ma'am, the Court clarified the statutory meaning of Term versus Tenure. Security of tenure guarantees protection against arbitrary dismissal DURING the term. Upon the expiration of the term, official relations terminate automatically by operation of law.\"",
        "conclusion": "The Supreme Court AFFIRMED the decision of the Court of Appeals, DISMISSING Aparri's petition for Mandamus and Quo Warranto.",
        "conclusion_plain": "The General Manager lost and his replacement was affirmed.",
        "conclusion_recite": "\"The Supreme Court dismissed the petition, ruling that expiration of term does not constitute illegal removal under Civil Service law.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - C. Presumptions: Distinction Between Term and Tenure (Presumption of Regularity in Executive Appointments)",
        "latin_maxims": [
            ("Omnia praesumuntur rite et solemniter esse acta (all acts are presumed to have been done regularly)", "All things are presumed regular.", "The appointment and term-fixing by the Board of Directors enjoy the presumption of regularity."),
            ("Cessante ratione legis, cessat ipsa lex (when the reason of the law ceases, the law itself ceases)", "When the reason for a law ceases, the law ceases.", "When the term of office expires, the right to hold office ceases automatically."),
            ("Verba legis non est recedendum (from the words of the statute there should be no departure)", "From the words of the statute there must be no departure.", "The explicit expiration date fixed in the appointment controls.")
        ],
        "primary_maxim": "Omnia praesumuntur rite et solemniter esse acta\n(all acts are presumed to have been done regularly / Board resolution fixing term of office is presumed regular and valid)",
        "secondary_maxims": "• Cessante ratione legis cessat ipsa lex (expiration of term extinguishes tenure)\n• Verba legis non est recedendum (adherence to appointment terms)",
        "violation_text": "The petitioner confused 'tenure' with 'term', attempting to convert a fixed-term appointment into permanent life tenure.",
        "execution_text": "Statutory Distinction Between Term and Tenure: 'Term' represents the legal period fixed for holding office; 'Tenure' is the actual incumbency. Expiration of term is an automatic statutory termination, not a disciplinary removal.",
        "statcon_plain": "A fixed-term job ends on the agreed expiration date; you cannot use the security of tenure law to turn a temporary job into a permanent lifetime seat.",
        "statcon_recite": "\"Sir/Ma'am, Aparri v. CA is the supreme authority on the statutory distinction between Term and Tenure under Civil Service law.\""
    },
    {
        "num": 68,
        "title": "Republic of the Philippines v. Court of Appeals and Roridel Olaviano Molina",
        "citation": "G.R. No. 108763 | February 13, 1997 | 268 SCRA 198 | En Banc | Ponente: J. Panganiban",
        "plaintiff": "Republic of the Philippines (Petitioner)",
        "defendant": "Court of Appeals and Roridel Olaviano Molina (Respondents)",
        "court": "Regional Trial Court of La Trinidad, Benguet (Branch 8) / Court of Appeals",
        "nature": "Petition for Review on Certiorari under Rule 45 concerning declaration of nullity of marriage under Article 36 of the Family Code (Psychological Incapacity) and Presumption in Favor of Marriage.",
        "facts": "Roridel Molina filed a petition to declare her marriage with Reynaldo Molina void ab initio under Article 36 of the Family Code, citing psychological incapacity. Roridel alleged that Reynaldo was highly immature, irresponsible, preferred spending time with barkada, failed to support the family, and abandoned them. The RTC and CA declared the marriage void ab initio, equating emotional incompatibility and irreconcilable differences with psychological incapacity. The Solicitor General appealed on behalf of the Republic, arguing that the lower courts violated the constitutional mandate and statutory presumption protecting marriage as an inviolable social institution.",
        "plain_facts": "A wife filed to nullify her marriage under Article 36 of the Family Code (Psychological Incapacity) because her husband was immature, spent all his time drinking with friends, and failed to provide financial support. The lower courts granted the annulment. The Supreme Court reversed the decision and laid down the famous 'Molina Guidelines', ruling that simple immaturity, refusal to support, or marital incompatibility is NOT psychological incapacity. Under the Constitution and Family Code, there is a powerful Presumption in Favor of Marriage (Semper Praesumitur Pro Matrimonio).",
        "issue": "Whether or not irreconcilable differences, immaturity, and failure to perform marital obligations constitute Psychological Incapacity under Article 36 of the Family Code, testing the Presumption in Favor of Marriage (Semper Praesumitur Pro Matrimonio).",
        "issue_plain": "Does being immature, irresponsible, and a bad provider count as 'psychological incapacity' to void a marriage, or does the law presume the marriage is valid?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether irreconcilable differences and marital neglect satisfy Article 36 of the Family Code, testing the canonical guideline and the bedrock canon Semper Praesumitur Pro Matrimonio (always presume in favor of marriage).\"",
        "answer": "NO. Irreconcilable differences, emotional incompatibility, and simple neglect of duties do NOT constitute Psychological Incapacity. Under Article 36 and the Constitution, there is a strong PRESUMPTION IN FAVOR OF THE VALIDITY OF MARRIAGE (Semper Praesumitur Pro Matrimonio).",
        "answer_plain": "No. Psychological incapacity is not mere bad behavior; it is a severe psychological illness that renders a person mentally incapable of understanding marital obligations. Because the law fiercely protects families, any doubt is resolved in favor of keeping the marriage intact.",
        "answer_recite": "\"No, Sir/Ma'am. As Justice Artemio Panganiban formulated in the historic Molina Guidelines: (1) burden of proof belongs to plaintiff; (2) root cause must be medically identified; (3) gravity, juridical antecedence, and incurability must be proved; and (4) under Semper praesumitur pro matrimonio (always presume in favor of marriage), all doubts are resolved in favor of the validity of the marriage.\"",
        "legal_basis": [
            ("1. Article 36, Family Code of the Philippines:", "Declaration of nullity of marriage based on psychological incapacity existing at the time of celebration."),
            ("2. Article 220, 1987 Constitution & Article 1, Family Code:", "Marriage is an inviolable social institution protected by the State."),
            ("3. Semper Praesumitur Pro Matrimonio (the presumption is always in favor of the validity of marriage):", "Fundamental statutory presumption in civil and canonical family law."),
            ("4. Strictissimi Juris in Marital Dissolution:", "Grounds for nullity of marriage are strictly construed to prevent easy de facto divorce.")
        ],
        "legal_basis_plain": "Article 36 Family Code, Molina Guidelines, and Semper Praesumitur Pro Matrimonio.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is Article 36 of the Family Code, governed by the canonical and constitutional presumption Semper praesumitur pro matrimonio (the presumption is always in favor of marriage).\"",
        "analysis": [
            ("1. The Constitutional Mandate Protecting Marriage:", "The 1987 Constitution explicitly protects marriage as the foundation of the family. Article 36 was never intended to be an easy divorce escape hatch."),
            ("2. The Three Essential Requisites:", "Psychological incapacity under Article 36 requires: (a) Gravity (truly serious and incipit); (b) Juridical Antecedence (existing prior to marriage); and (c) Incurability."),
            ("3. Failure vs. Incapacity:", "Mere refusal, difficulty, or neglect to perform marital duties is NOT psychological incapacity. Incapacity means a psychological illness so severe that the party is mentally incapable of understanding the basic marital covenant.")
        ],
        "analysis_plain": "The Court explained that psychological incapacity is not a divorce coupon you get because your spouse is annoying, lazy, or irresponsible. It must be a severe mental illness rooted before the wedding that makes marriage impossible. The law always presumes a marriage is valid unless overwhelming psychiatric proof is shown.",
        "analysis_recite": "\"Sir/Ma'am, the Court laid down the 8 Molina Guidelines. Under Semper Praesumitur Pro Matrimonio, the law strictly presumes the validity of marriage. Because the evidence showed only irreconcilable differences and financial neglect, the statutory threshold of Article 36 was not met.\"",
        "conclusion": "The Supreme Court GRANTED the petition of the Republic, REVERSED the CA, and DECLARED the marriage between Roridel and Reynaldo Molina VALID AND SUBSISTING.",
        "conclusion_plain": "The marriage was declared valid and the nullity petition was denied.",
        "conclusion_recite": "\"The Supreme Court reversed the annulment and upheld the validity of the marriage under the Molina Guidelines and Semper Praesumitur Pro Matrimonio.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - C. Presumptions: Presumption in Favor of Marriage (Semper Praesumitur Pro Matrimonio) & Canonical Construction",
        "latin_maxims": [
            ("Semper praesumitur pro matrimonio (the presumption is always in favor of marriage)", "Always presume in favor of marriage.", "All doubts in Article 36 proceedings are resolved in favor of the validity and indissolubility of marriage."),
            ("Strictissimi juris (of the strictest interpretation)", "Of the strictest law.", "Provisions authorizing the nullity of marriage are strictly construed to preserve social stability."),
            ("Salus populi est suprema lex (the welfare of the people is the supreme law)", "The welfare of the people is the supreme law.", "Preserving the stability of the family as a basic social institution is paramount.")
        ],
        "primary_maxim": "Semper praesumitur pro matrimonio\n(the presumption is always in favor of marriage / Article 36 Family Code is construed strictly to uphold marital validity under the Molina Guidelines)",
        "secondary_maxims": "• Strictissimi juris (strict construction of nullity grounds)\n• Salus populi est suprema lex (constitutional protection of the family)",
        "violation_text": "The lower courts diluted Article 36 by treating simple irreconcilable differences as psychological incapacity, violating the Presumption in Favor of Marriage.",
        "execution_text": "Presumption in Favor of Marriage: Under Semper Praesumitur Pro Matrimonio, every intendment of the law leans toward the validity and survival of marriage; psychological incapacity requires clear proof of gravity, antecedence, and incurability.",
        "statcon_plain": "The law strongly protects marriage; courts will always presume a marriage is valid and will not allow couples to dissolve it over ordinary marital arguments.",
        "statcon_recite": "\"Sir/Ma'am, Republic v. Molina is the legendary landmark decision establishing the Molina Guidelines and the statutory presumption Semper praesumitur pro matrimonio under Article 36.\""
    },
    {
        "num": 69,
        "title": "Lawyers Against Monopoly and Poverty (LAMP) v. The Secretary of Budget and Management",
        "citation": "G.R. No. 164987 | April 24, 2012 | 670 SCRA 373 | En Banc | Ponente: J. Mendoza",
        "plaintiff": "Lawyers Against Monopoly and Poverty (LAMP) (Petitioner)",
        "defendant": "The Secretary of Budget and Management, Senate President, and Speaker of the House (Respondents)",
        "court": "Supreme Court En Banc (Original Action for Certiorari and Prohibition)",
        "nature": "Petition for Certiorari and Prohibition challenging the constitutionality of the Priority Development Assistance Fund (PDAF / Pork Barrel) under the General Appropriations Act of 2004.",
        "facts": "Lawyers Against Monopoly and Poverty (LAMP) filed a petition challenging the constitutionality of the Priority Development Assistance Fund (PDAF) provisions in the 2004 General Appropriations Act (R.A. No. 9206). LAMP argued that the PDAF system was unconstitutional on its face because it allowed members of Congress to identify specific infrastructure projects after the enactment of the budget, thereby violating the separation of powers and non-delegation of legislative power. However, LAMP presented no concrete evidence of actual post-enactment legislator project execution in the 2004 budget, relying solely on theoretical arguments.",
        "plain_facts": "A group of lawyers filed a petition claiming the 2004 Pork Barrel (PDAF) budget law was unconstitutional on its face because lawmakers secretly direct project spending. However, the petitioners failed to bring any concrete financial proof or audit reports to prove that the 2004 budget line-items were illegally handled. The Supreme Court dismissed the petition under the Presumption of Constitutionality, ruling that courts will not declare an entire national budget law unconstitutional without clear, convincing factual evidence. (Note: The PDAF system was later declared unconstitutional with full evidentiary records in the 2013 Belgica case).",
        "issue": "Whether or not the PDAF provisions in the 2004 GAA can be declared unconstitutional without clear factual proof of constitutional violation, testing the Presumption of Constitutionality of Appropriations Statutes.",
        "issue_plain": "Can the Supreme Court strike down a national budget law as unconstitutional based on pure theory without actual evidence of illegality?",
        "issue_recite": "\"Sir/Ma'am, the issue is whether the 2004 PDAF budget provisions can be invalidated based on theoretical assertions, testing the Presumption of Constitutionality and the burden of proof required to invalidate a statute.\"",
        "answer": "NO. The 2004 PDAF provisions CANNOT be declared unconstitutional in the absence of clear, compelling factual evidence. Under the PRESUMPTION OF CONSTITUTIONALITY, every legislative act is presumed valid, and the burden of proving unconstitutionality rests heavily upon the petitioner.",
        "answer_plain": "No. The Supreme Court cannot strike down a law passed by Congress based on theories alone. Because every statute is presumed constitutional, the petitioner must present real, undeniable proof of violation. Speculation is not enough.",
        "answer_recite": "\"No, Sir/Ma'am. The Supreme Court held that under the Presumption of Constitutionality, every statute is presumed to have been enacted in conformity with the Constitution. To strike down a provision in a General Appropriations Act, the petitioner must overcome this presumption with clear and convincing evidence, not mere conjectures or newspaper allegations.\"",
        "legal_basis": [
            ("1. Republic Act No. 9206 (General Appropriations Act of 2004):", "Statutory allocation for the Priority Development Assistance Fund (PDAF)."),
            ("2. Presumption of Constitutionality of Statutes:", "Statutes carry a heavy presumption of validity; nullity will be declared only upon a clear and unequivocal breach of the Constitution."),
            ("3. Omnia Praesumuntur Rite Esse Acta (all acts are presumed regular):", "Official budget disbursements are presumed regular in the absence of contrary evidence.")
        ],
        "legal_basis_plain": "RA 9206 (2004 GAA), Presumption of Constitutionality, and Omnia Praesumuntur Rite Esse Acta.",
        "legal_basis_recite": "\"Sir/Ma'am, the legal basis is RA 9206, governed by the Presumption of Constitutionality and Omnia praesumuntur rite et solemniter esse acta (all official acts are presumed regular).\"",
        "analysis": [
            ("1. Heavy Burden on Challengers:", "To overcome the presumption of constitutionality, the petitioner must demonstrate that the law is clearly, plainly, and palpably in conflict with the Constitution. Mere speculation is insufficient."),
            ("2. Facial Validity of 2004 PDAF Text:", "On its face, the text of the 2004 GAA assigned project implementation to executive departments (DPWH, DOH, etc.), which is constitutionally permissible on paper."),
            ("3. Evolution to Belgica v. Ochoa (2013):", "While the 2004 budget survived in LAMP due to lack of evidence, the Supreme Court later struck down the entire PDAF system in Belgica v. Ochoa (2013) when COA Special Audit Reports provided overwhelming empirical proof of post-enactment legislative control.")
        ],
        "analysis_plain": "To destroy a law, you must bring proof, not just opinions. On paper, the 2004 budget looked normal because it said government departments would spend the money. Because the petitioners brought zero audit reports or proof of abuse, the presumption of constitutionality saved the law. (Later in 2013, COA provided the actual proof in the Belgica case, and the pork barrel was struck down).",
        "analysis_recite": "\"Sir/Ma'am, the Court applied the Presumption of Constitutionality. A statute cannot be nullified on mere facial assertions without empirical proof of unconstitutional execution. The Court reaffirmed that the judiciary will not invalidate an act of Congress unless unconstitutionality is shown beyond reasonable doubt.\"",
        "conclusion": "The Supreme Court DISMISSED the petition for lack of merit, UPHOLDING the constitutionality of the 2004 PDAF provisions under the Presumption of Constitutionality.",
        "conclusion_plain": "The petition was dismissed and the 2004 budget law was upheld under the presumption of constitutionality.",
        "conclusion_recite": "\"The Supreme Court dismissed the petition, reaffirming the Presumption of Constitutionality of General Appropriations Acts in the absence of factual proof.\"",
        "syllabus": "• Chapter IV: Aids to Construction\n  - C. Presumptions: Presumption of Constitutionality of Appropriations Acts (Burden of Proof & Evolution to Belgica)",
        "latin_maxims": [
            ("Omnia praesumuntur rite et solemniter esse acta donec probetur in contrarium (all acts are presumed to have been done regularly and with solemnity until the contrary is proved)", "All acts are presumed regular until proved otherwise.", "The General Appropriations Act enjoys a strong presumption of constitutional validity."),
            ("Actori incumbit onus probandi (the burden of proof rests on the plaintiff)", "The burden of proof lies on the claimant.", "The petitioner bears the heavy burden of establishing the unconstitutionality of a statute beyond doubt."),
            ("Judicis est ius dicere, non dare (it is the duty of a judge to declare the law, not to make it)", "The judge declares the law, not makes it.", "Courts will not strike down legislative appropriations on speculative grounds.")
        ],
        "primary_maxim": "Omnia praesumuntur rite et solemniter esse acta\n(all acts are presumed to have been done regularly / Presumption of Constitutionality of legislative appropriations acts)",
        "secondary_maxims": "• Actori incumbit onus probandi (burden of proof lies on the challenger)\n• Judicis est ius dicere non dare (judicial restraint in reviewing fiscal statutes)",
        "violation_text": "The petitioner attempted to nullify an act of Congress based on theoretical arguments without presenting evidentiary proof to overcome the Presumption of Constitutionality.",
        "execution_text": "Overcoming the Presumption of Constitutionality: A statute will not be declared unconstitutional unless the violation is clear, complete, and established by undeniable factual and legal demonstration.",
        "statcon_plain": "Every law passed by Congress is presumed valid; you cannot ask judges to destroy a budget law without presenting solid evidence of abuse.",
        "statcon_recite": "\"Sir/Ma'am, LAMP v. DBM is the leading authority on the Presumption of Constitutionality in General Appropriations Acts—a statute will not be nullified without empirical proof.\""
    }
]

print(f"Loaded {len(cases_p3_part2)} cases for Phase 3 Part 2 (Cases 60-69).")
